#!/usr/bin/env python3
"""Generate offline speak-trainer workplace datasets."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "content" / "speak"


def item(
    id_: str,
    category: str,
    level: str,
    target: str,
    target_id: str,
    chunks: list[str],
    scrambled: list[str],
    keywords: list[str],
    patterns: list[str],
    errors: list[str],
    scenario: str,
    scenario_id: str,
    models: list[str] | None = None,
) -> dict:
    return {
        "id": id_,
        "category": category,
        "level": level,
        "target": target,
        "targetId": target_id,
        "chunks": chunks,
        "scrambled": scrambled,
        "keywords": keywords,
        "grammarPatterns": patterns,
        "commonErrors": errors,
        "scenario": scenario,
        "scenarioId": scenario_id,
        "modelAnswers": models or [target],
        "audio": None,
    }


IT = [
    item(
        "it_ops_001",
        "IT Operations",
        "junior",
        "I've already checked the server, and everything looks normal.",
        "Saya sudah memeriksa server, dan semuanya terlihat normal.",
        ["I've already checked", "the server", "and everything looks normal"],
        ["already", "server", "I've", "checked", "the", "and", "everything", "looks", "normal"],
        ["checked", "server", "normal"],
        ["present_perfect"],
        ["I already check the server", "I already checked server"],
        "Your supervisor asks: What's the status of the server?",
        "Supervisor Anda bertanya: Bagaimana status server-nya?",
    ),
    item(
        "it_ops_002",
        "IT Operations",
        "junior",
        "I'll investigate the issue and update you shortly.",
        "Saya akan menyelidiki masalahnya dan mengabari Anda sebentar lagi.",
        ["I'll investigate", "the issue", "and update you shortly"],
        ["investigate", "I'll", "the", "issue", "and", "update", "you", "shortly"],
        ["investigate", "issue", "update"],
        ["future_will"],
        ["I will investigate the issue and update you short"],
        "Your manager asks: Can you look into this alert?",
        "Manager Anda bertanya: Bisa Anda cek alert ini?",
    ),
    item(
        "it_ops_003",
        "IT Operations",
        "mid",
        "We've rolled back the deployment because error rates spiked.",
        "Kami sudah rollback deployment karena error rate melonjak.",
        ["We've rolled back", "the deployment", "because error rates spiked"],
        ["We've", "rolled", "back", "the", "deployment", "because", "error", "rates", "spiked"],
        ["rolled", "deployment", "error"],
        ["present_perfect", "cause_clause"],
        ["We roll back the deployment because error rate spike"],
        "Incident bridge: Why did you roll back?",
        "Incident bridge: Kenapa Anda rollback?",
    ),
    item(
        "it_ops_004",
        "IT Operations",
        "mid",
        "The database failover completed successfully within two minutes.",
        "Failover database selesai sukses dalam dua menit.",
        ["The database failover", "completed successfully", "within two minutes"],
        ["The", "database", "failover", "completed", "successfully", "within", "two", "minutes"],
        ["failover", "completed", "minutes"],
        ["past_simple"],
        ["The database failover complete successfully in two minute"],
        "Ops asks: Did failover finish?",
        "Ops bertanya: Apakah failover sudah selesai?",
    ),
    item(
        "it_ops_005",
        "IT Operations",
        "junior",
        "I'm monitoring the latency metrics right now.",
        "Saya sedang memantau metrik latensi saat ini.",
        ["I'm monitoring", "the latency metrics", "right now"],
        ["I'm", "monitoring", "the", "latency", "metrics", "right", "now"],
        ["monitoring", "latency", "metrics"],
        ["present_continuous"],
        ["I monitoring the latency metric now"],
        "Manager: What are you doing now?",
        "Manager: Sedang apa Anda sekarang?",
    ),
    item(
        "it_ops_006",
        "IT Operations",
        "senior",
        "If the queue keeps growing, we'll scale the workers horizontally.",
        "Jika antrian terus tumbuh, kami akan scale worker secara horizontal.",
        ["If the queue keeps growing", "we'll scale", "the workers horizontally"],
        ["If", "the", "queue", "keeps", "growing", "we'll", "scale", "the", "workers", "horizontally"],
        ["queue", "scale", "workers"],
        ["conditional_if"],
        ["If the queue keep growing we will scale the worker horizontal"],
        "On-call asks: What's the next step if backlog rises?",
        "On-call bertanya: Langkah berikutnya jika backlog naik?",
    ),
    item(
        "it_ops_007",
        "IT Operations",
        "mid",
        "Please restart the service after clearing the cache.",
        "Tolong restart service setelah membersihkan cache.",
        ["Please restart", "the service", "after clearing the cache"],
        ["Please", "restart", "the", "service", "after", "clearing", "the", "cache"],
        ["restart", "service", "cache"],
        ["imperative"],
        ["Please restart service after clear the cache"],
        "Junior asks how to recover a stuck worker.",
        "Junior bertanya cara recover worker yang stuck.",
    ),
    item(
        "it_ops_008",
        "IT Operations",
        "junior",
        "The alert was a false positive caused by a flaky probe.",
        "Alert itu false positive karena probe yang flaky.",
        ["The alert was", "a false positive", "caused by a flaky probe"],
        ["The", "alert", "was", "a", "false", "positive", "caused", "by", "a", "flaky", "probe"],
        ["alert", "false", "probe"],
        ["passive"],
        ["The alert is false positive because flaky probe"],
        "Manager: Was that a real outage?",
        "Manager: Apakah itu outage sungguhan?",
    ),
    item(
        "it_ops_009",
        "IT Operations",
        "senior",
        "We've mitigated the issue, and I'm writing the postmortem notes.",
        "Kami sudah mitigasi masalahnya, dan saya sedang menulis catatan postmortem.",
        ["We've mitigated the issue", "and I'm writing", "the postmortem notes"],
        ["We've", "mitigated", "the", "issue", "and", "I'm", "writing", "the", "postmortem", "notes"],
        ["mitigated", "postmortem", "writing"],
        ["present_perfect", "present_continuous"],
        ["We mitigate the issue and I writing the postmortem"],
        "After an incident: What's the current status?",
        "Setelah incident: Bagaimana status saat ini?",
    ),
    item(
        "it_ops_010",
        "IT Operations",
        "mid",
        "I'll page the platform team if the disk fills above ninety percent.",
        "Saya akan page tim platform jika disk terisi di atas sembilan puluh persen.",
        ["I'll page", "the platform team", "if the disk fills above ninety percent"],
        ["I'll", "page", "the", "platform", "team", "if", "the", "disk", "fills", "above", "ninety", "percent"],
        ["page", "disk", "percent"],
        ["future_will", "conditional_if"],
        ["I will page platform team if disk fill above ninety percent"],
        "On-call runbook: When do you escalate?",
        "Runbook on-call: Kapan Anda escalate?",
    ),
]

REPORT = [
    item(
        "rep_001",
        "Reporting",
        "junior",
        "I've finished the migration, and I'm verifying the connections now.",
        "Saya sudah menyelesaikan migrasi, dan sedang memverifikasi koneksi sekarang.",
        ["I've finished the migration", "and I'm verifying", "the connections now"],
        ["I've", "finished", "the", "migration", "and", "I'm", "verifying", "the", "connections", "now"],
        ["finished", "migration", "verifying"],
        ["present_perfect", "present_continuous"],
        ["I finish the migration and I verifying the connection"],
        "Your supervisor asks: What's the status of the server migration?",
        "Supervisor: Bagaimana status migrasi server?",
    ),
    item(
        "rep_002",
        "Reporting",
        "mid",
        "We're about half a day behind schedule due to flaky tests.",
        "Kami mundur sekitar setengah hari dari jadwal karena tes yang flaky.",
        ["We're about half a day behind", "schedule", "due to flaky tests"],
        ["We're", "about", "half", "a", "day", "behind", "schedule", "due", "to", "flaky", "tests"],
        ["behind", "schedule", "flaky"],
        ["present_continuous", "cause_clause"],
        ["We about half day behind schedule because flaky test"],
        "Standup: Are you on track for today's estimate?",
        "Standup: Apakah Anda on track untuk estimasi hari ini?",
    ),
    item(
        "rep_003",
        "Reporting",
        "junior",
        "I need more time to investigate the root cause.",
        "Saya butuh lebih banyak waktu untuk menyelidiki root cause.",
        ["I need more time", "to investigate", "the root cause"],
        ["I", "need", "more", "time", "to", "investigate", "the", "root", "cause"],
        ["need", "investigate", "root"],
        ["infinitive"],
        ["I need more time for investigate root cause"],
        "Manager: When will you have an update?",
        "Manager: Kapan Anda punya update?",
    ),
    item(
        "rep_004",
        "Reporting",
        "senior",
        "Customer impact is limited to the checkout API in the EU region.",
        "Dampak ke pelanggan terbatas pada checkout API di wilayah EU.",
        ["Customer impact is limited", "to the checkout API", "in the EU region"],
        ["Customer", "impact", "is", "limited", "to", "the", "checkout", "API", "in", "the", "EU", "region"],
        ["impact", "checkout", "EU"],
        ["passive"],
        ["Customer impact limited to checkout API in EU region"],
        "Exec asks: What's the customer impact?",
        "Exec bertanya: Apa dampak ke pelanggan?",
    ),
    item(
        "rep_005",
        "Reporting",
        "mid",
        "I'll send a written update by the end of the day.",
        "Saya akan kirim update tertulis sebelum akhir hari.",
        ["I'll send", "a written update", "by the end of the day"],
        ["I'll", "send", "a", "written", "update", "by", "the", "end", "of", "the", "day"],
        ["send", "update", "day"],
        ["future_will"],
        ["I will send written update at the end of day"],
        "Your lead asks for a status note.",
        "Lead Anda minta catatan status.",
    ),
    item(
        "rep_006",
        "Reporting",
        "junior",
        "Yesterday I fixed the auth bug, and today I'm writing tests.",
        "Kemarin saya memperbaiki bug auth, dan hari ini saya menulis tes.",
        ["Yesterday I fixed", "the auth bug", "and today I'm writing tests"],
        ["Yesterday", "I", "fixed", "the", "auth", "bug", "and", "today", "I'm", "writing", "tests"],
        ["fixed", "auth", "tests"],
        ["past_simple", "present_continuous"],
        ["Yesterday I fix the auth bug and today I writing test"],
        "Standup: Give your yesterday / today update.",
        "Standup: Berikan update yesterday / today Anda.",
    ),
    item(
        "rep_007",
        "Reporting",
        "mid",
        "The blocker is missing staging credentials from the platform team.",
        "Blocker-nya adalah kredensial staging yang belum ada dari tim platform.",
        ["The blocker is", "missing staging credentials", "from the platform team"],
        ["The", "blocker", "is", "missing", "staging", "credentials", "from", "the", "platform", "team"],
        ["blocker", "credentials", "platform"],
        ["present_simple"],
        ["The blocker is miss staging credential from platform team"],
        "Standup: Any blockers?",
        "Standup: Ada blocker?",
    ),
    item(
        "rep_008",
        "Reporting",
        "senior",
        "I recommend we postpone the release until the flake is quarantined.",
        "Saya merekomendasikan kita tunda rilis sampai flake di-quarantine.",
        ["I recommend we postpone", "the release", "until the flake is quarantined"],
        ["I", "recommend", "we", "postpone", "the", "release", "until", "the", "flake", "is", "quarantined"],
        ["recommend", "postpone", "flake"],
        ["subjunctive_recommend", "passive"],
        ["I recommend we postpone the release until the flake quarantine"],
        "Release review: Should we ship tonight?",
        "Release review: Apakah kita ship malam ini?",
    ),
    item(
        "rep_009",
        "Reporting",
        "junior",
        "I've attached the logs and screenshots in the ticket.",
        "Saya sudah melampirkan log dan screenshot di tiket.",
        ["I've attached", "the logs and screenshots", "in the ticket"],
        ["I've", "attached", "the", "logs", "and", "screenshots", "in", "the", "ticket"],
        ["attached", "logs", "ticket"],
        ["present_perfect"],
        ["I attach the log and screenshot in the ticket"],
        "Support asks where the evidence is.",
        "Support bertanya di mana buktinya.",
    ),
    item(
        "rep_010",
        "Reporting",
        "mid",
        "Risk is medium because only internal tools are affected.",
        "Risikonya menengah karena hanya tools internal yang terdampak.",
        ["Risk is medium", "because only internal tools", "are affected"],
        ["Risk", "is", "medium", "because", "only", "internal", "tools", "are", "affected"],
        ["risk", "medium", "affected"],
        ["present_simple", "passive"],
        ["Risk is medium because only internal tool affected"],
        "Manager: What's the risk level?",
        "Manager: Bagaimana level risikonya?",
    ),
]

DAILY = [
    item(
        "day_001",
        "Daily Office",
        "junior",
        "Can we move our one-on-one to tomorrow afternoon?",
        "Bisakah kita pindahkan one-on-one ke besok sore?",
        ["Can we move", "our one-on-one", "to tomorrow afternoon"],
        ["Can", "we", "move", "our", "one-on-one", "to", "tomorrow", "afternoon"],
        ["move", "one-on-one", "tomorrow"],
        ["modal_can"],
        ["Can we move our one on one to tomorrow afternoon"],
        "You need to reschedule a meeting politely.",
        "Anda perlu menjadwal ulang meeting dengan sopan.",
    ),
    item(
        "day_002",
        "Daily Office",
        "junior",
        "I'll get back to you after I check with the team.",
        "Saya akan kembali mengabari setelah saya cek dengan tim.",
        ["I'll get back to you", "after I check", "with the team"],
        ["I'll", "get", "back", "to", "you", "after", "I", "check", "with", "the", "team"],
        ["get", "back", "team"],
        ["future_will"],
        ["I will get back to you after I checking with the team"],
        "A colleague asks for an immediate answer you don't have yet.",
        "Rekan minta jawaban segera yang belum Anda miliki.",
    ),
    item(
        "day_003",
        "Daily Office",
        "mid",
        "Thanks for the update — that helps a lot.",
        "Terima kasih atas updatenya — itu sangat membantu.",
        ["Thanks for the update", "that helps", "a lot"],
        ["Thanks", "for", "the", "update", "that", "helps", "a", "lot"],
        ["thanks", "update", "helps"],
        ["present_simple"],
        ["Thank for the update that help a lot"],
        "Someone just shared a clear status in Slack.",
        "Seseorang baru saja berbagi status jelas di Slack.",
    ),
    item(
        "day_004",
        "Daily Office",
        "junior",
        "I'm unavailable from two to three for a dentist appointment.",
        "Saya tidak tersedia dari jam dua sampai tiga untuk janji dokter gigi.",
        ["I'm unavailable", "from two to three", "for a dentist appointment"],
        ["I'm", "unavailable", "from", "two", "to", "three", "for", "a", "dentist", "appointment"],
        ["unavailable", "dentist", "appointment"],
        ["present_simple"],
        ["I unavailable from two to three for dentist appointment"],
        "You need to block focus time on the calendar.",
        "Anda perlu memblokir waktu di kalender.",
    ),
    item(
        "day_005",
        "Daily Office",
        "mid",
        "Could you share the latest draft when you have a moment?",
        "Bisakah Anda bagikan draft terbaru ketika ada waktu?",
        ["Could you share", "the latest draft", "when you have a moment"],
        ["Could", "you", "share", "the", "latest", "draft", "when", "you", "have", "a", "moment"],
        ["share", "draft", "moment"],
        ["modal_could"],
        ["Could you share the latest draft when you have moment"],
        "Ask politely for a document.",
        "Minta dokumen dengan sopan.",
    ),
    item(
        "day_006",
        "Daily Office",
        "junior",
        "Let me know if you need any help with the ticket.",
        "Kabari saya jika Anda butuh bantuan untuk tiket itu.",
        ["Let me know", "if you need any help", "with the ticket"],
        ["Let", "me", "know", "if", "you", "need", "any", "help", "with", "the", "ticket"],
        ["help", "ticket", "know"],
        ["imperative", "conditional_if"],
        ["Let me know if you need help with ticket"],
        "Offer help after assigning a task.",
        "Tawarkan bantuan setelah assign tugas.",
    ),
    item(
        "day_007",
        "Daily Office",
        "mid",
        "I'm looping in the security team for a second look.",
        "Saya mengajak tim security untuk melihat sekali lagi.",
        ["I'm looping in", "the security team", "for a second look"],
        ["I'm", "looping", "in", "the", "security", "team", "for", "a", "second", "look"],
        ["looping", "security", "look"],
        ["present_continuous"],
        ["I looping in the security team for second look"],
        "Explain why you CC'd another team.",
        "Jelaskan kenapa Anda CC tim lain.",
    ),
    item(
        "day_008",
        "Daily Office",
        "junior",
        "Sorry for the delayed reply — I was in back-to-back meetings.",
        "Maaf balasan terlambat — saya ada meeting beruntun.",
        ["Sorry for the delayed reply", "I was in", "back-to-back meetings"],
        ["Sorry", "for", "the", "delayed", "reply", "I", "was", "in", "back-to-back", "meetings"],
        ["sorry", "delayed", "meetings"],
        ["past_simple"],
        ["Sorry for delayed reply I was in back to back meeting"],
        "Apologize for a late Slack reply.",
        "Minta maaf karena balasan Slack terlambat.",
    ),
]

MEET = [
    item(
        "mtg_001",
        "Meetings",
        "mid",
        "Let's park this topic and revisit it next week.",
        "Mari kita parkir topik ini dan bahas lagi minggu depan.",
        ["Let's park this topic", "and revisit it", "next week"],
        ["Let's", "park", "this", "topic", "and", "revisit", "it", "next", "week"],
        ["park", "revisit", "week"],
        ["suggestive_imperative"],
        ["Let us park this topic and revisit it next week"],
        "Facilitate when a discussion is going too long.",
        "Fasilitasi ketika diskusi terlalu panjang.",
    ),
    item(
        "mtg_002",
        "Meetings",
        "junior",
        "Can everyone mute when they're not speaking?",
        "Bisakah semua mute ketika tidak berbicara?",
        ["Can everyone mute", "when they're not speaking"],
        ["Can", "everyone", "mute", "when", "they're", "not", "speaking"],
        ["mute", "speaking"],
        ["modal_can"],
        ["Can everyone mute when they not speaking"],
        "There's background noise on the call.",
        "Ada noise di background pada call.",
    ),
    item(
        "mtg_003",
        "Meetings",
        "mid",
        "The decision is to ship the hotfix today and monitor closely.",
        "Keputusannya adalah ship hotfix hari ini dan pantau ketat.",
        ["The decision is", "to ship the hotfix today", "and monitor closely"],
        ["The", "decision", "is", "to", "ship", "the", "hotfix", "today", "and", "monitor", "closely"],
        ["decision", "hotfix", "monitor"],
        ["infinitive"],
        ["The decision is ship the hotfix today and monitor close"],
        "Summarize the meeting decision.",
        "Ringkas keputusan meeting.",
    ),
    item(
        "mtg_004",
        "Meetings",
        "senior",
        "I'd like to challenge that assumption with the latest metrics.",
        "Saya ingin menantang asumsi itu dengan metrik terbaru.",
        ["I'd like to challenge", "that assumption", "with the latest metrics"],
        ["I'd", "like", "to", "challenge", "that", "assumption", "with", "the", "latest", "metrics"],
        ["challenge", "assumption", "metrics"],
        ["modal_would"],
        ["I like to challenge that assumption with latest metric"],
        "Disagree politely with data.",
        "Tidak setuju dengan sopan memakai data.",
    ),
    item(
        "mtg_005",
        "Meetings",
        "junior",
        "Could you clarify what success looks like for this milestone?",
        "Bisakah Anda klarifikasi seperti apa kesuksesan untuk milestone ini?",
        ["Could you clarify", "what success looks like", "for this milestone"],
        ["Could", "you", "clarify", "what", "success", "looks", "like", "for", "this", "milestone"],
        ["clarify", "success", "milestone"],
        ["modal_could", "wh_clause"],
        ["Could you clarify what success look like for this milestone"],
        "Ask for clearer acceptance criteria.",
        "Minta kriteria acceptance yang lebih jelas.",
    ),
    item(
        "mtg_006",
        "Meetings",
        "mid",
        "Action item: I'll draft the proposal by Friday.",
        "Action item: Saya akan draft proposal paling lambat Jumat.",
        ["Action item", "I'll draft the proposal", "by Friday"],
        ["Action", "item", "I'll", "draft", "the", "proposal", "by", "Friday"],
        ["action", "draft", "Friday"],
        ["future_will"],
        ["Action item I will draft the proposal by Friday"],
        "Capture owners at the end of a meeting.",
        "Catat owner di akhir meeting.",
    ),
    item(
        "mtg_007",
        "Meetings",
        "senior",
        "We're aligning on scope before we commit to the timeline.",
        "Kami menyelaraskan scope sebelum commit ke timeline.",
        ["We're aligning on scope", "before we commit", "to the timeline"],
        ["We're", "aligning", "on", "scope", "before", "we", "commit", "to", "the", "timeline"],
        ["aligning", "scope", "timeline"],
        ["present_continuous"],
        ["We aligning on scope before we commit to the timeline"],
        "Explain why you won't lock dates yet.",
        "Jelaskan kenapa tanggal belum dikunci.",
    ),
    item(
        "mtg_008",
        "Meetings",
        "junior",
        "Sorry, I missed that — could you repeat the last point?",
        "Maaf, saya melewatkan itu — bisakah Anda ulangi poin terakhir?",
        ["Sorry I missed that", "could you repeat", "the last point"],
        ["Sorry", "I", "missed", "that", "could", "you", "repeat", "the", "last", "point"],
        ["missed", "repeat", "point"],
        ["past_simple", "modal_could"],
        ["Sorry I miss that could you repeat the last point"],
        "You lost audio for a few seconds.",
        "Audio Anda putus beberapa detik.",
    ),
]

PROBLEM = [
    item(
        "prob_001",
        "Problem Solving",
        "mid",
        "The root cause was a missing index on the orders table.",
        "Root cause-nya adalah index yang hilang di tabel orders.",
        ["The root cause was", "a missing index", "on the orders table"],
        ["The", "root", "cause", "was", "a", "missing", "index", "on", "the", "orders", "table"],
        ["root", "index", "orders"],
        ["past_simple"],
        ["The root cause is missing index on orders table"],
        "Explain the root cause briefly.",
        "Jelaskan root cause secara singkat.",
    ),
    item(
        "prob_002",
        "Problem Solving",
        "senior",
        "We should add a circuit breaker to protect the payment service.",
        "Kita harus menambah circuit breaker untuk melindungi payment service.",
        ["We should add", "a circuit breaker", "to protect the payment service"],
        ["We", "should", "add", "a", "circuit", "breaker", "to", "protect", "the", "payment", "service"],
        ["circuit", "breaker", "payment"],
        ["modal_should"],
        ["We should add circuit breaker to protect payment service"],
        "Propose a preventive fix.",
        "Usulkan perbaikan preventif.",
    ),
    item(
        "prob_003",
        "Problem Solving",
        "junior",
        "I reproduced the bug on staging with the same payload.",
        "Saya mereproduksi bug di staging dengan payload yang sama.",
        ["I reproduced the bug", "on staging", "with the same payload"],
        ["I", "reproduced", "the", "bug", "on", "staging", "with", "the", "same", "payload"],
        ["reproduced", "staging", "payload"],
        ["past_simple"],
        ["I reproduce the bug on staging with same payload"],
        "Confirm the bug is real.",
        "Konfirmasi bug itu nyata.",
    ),
    item(
        "prob_004",
        "Problem Solving",
        "mid",
        "As a workaround, we're routing traffic to the healthy region.",
        "Sebagai workaround, kami mengalihkan traffic ke region yang sehat.",
        ["As a workaround", "we're routing traffic", "to the healthy region"],
        ["As", "a", "workaround", "we're", "routing", "traffic", "to", "the", "healthy", "region"],
        ["workaround", "routing", "region"],
        ["present_continuous"],
        ["As workaround we routing traffic to the healthy region"],
        "Describe the temporary mitigation.",
        "Jelaskan mitigasi sementara.",
    ),
    item(
        "prob_005",
        "Problem Solving",
        "senior",
        "The long-term fix is to redesign the retry logic with jitter.",
        "Perbaikan jangka panjang adalah mendesain ulang retry logic dengan jitter.",
        ["The long-term fix is", "to redesign the retry logic", "with jitter"],
        ["The", "long-term", "fix", "is", "to", "redesign", "the", "retry", "logic", "with", "jitter"],
        ["long-term", "retry", "jitter"],
        ["infinitive"],
        ["The long term fix is redesign the retry logic with jitter"],
        "Separate short-term vs long-term fix.",
        "Pisahkan perbaikan jangka pendek vs panjang.",
    ),
    item(
        "prob_006",
        "Problem Solving",
        "junior",
        "I haven't found any errors in the application logs yet.",
        "Saya belum menemukan error di log aplikasi.",
        ["I haven't found", "any errors", "in the application logs yet"],
        ["I", "haven't", "found", "any", "errors", "in", "the", "application", "logs", "yet"],
        ["haven't", "errors", "logs"],
        ["present_perfect_negative"],
        ["I don't found any error in the application log yet"],
        "Report negative findings honestly.",
        "Laporkan temuan negatif dengan jujur.",
    ),
    item(
        "prob_007",
        "Problem Solving",
        "mid",
        "Latency dropped after we increased the connection pool size.",
        "Latensi turun setelah kami memperbesar ukuran connection pool.",
        ["Latency dropped", "after we increased", "the connection pool size"],
        ["Latency", "dropped", "after", "we", "increased", "the", "connection", "pool", "size"],
        ["latency", "dropped", "pool"],
        ["past_simple"],
        ["Latency drop after we increase the connection pool size"],
        "Explain what improved the metrics.",
        "Jelaskan apa yang memperbaiki metrik.",
    ),
    item(
        "prob_008",
        "Problem Solving",
        "senior",
        "Before we change production, let's validate the fix on canary.",
        "Sebelum mengubah production, mari validasi fix di canary.",
        ["Before we change production", "let's validate the fix", "on canary"],
        ["Before", "we", "change", "production", "let's", "validate", "the", "fix", "on", "canary"],
        ["validate", "canary", "production"],
        ["suggestive_imperative"],
        ["Before we change production let us validate the fix on canary"],
        "Push back on a risky hot-fix.",
        "Tolak hot-fix berisiko dengan sopan.",
    ),
    item(
        "prob_009",
        "Problem Solving",
        "junior",
        "The server has already been fixed, and I checked the database.",
        "Server sudah diperbaiki, dan saya sudah memeriksa database.",
        ["The server has already been fixed", "and I checked", "the database"],
        ["The", "server", "has", "already", "been", "fixed", "and", "I", "checked", "the", "database"],
        ["fixed", "checked", "database"],
        ["present_perfect_passive", "past_simple"],
        ["The server already fixed and I check the database"],
        "Your supervisor asks: What's the status of the server?",
        "Supervisor: Bagaimana status server?",
    ),
    item(
        "prob_010",
        "Problem Solving",
        "mid",
        "I'll document the steps so the next on-call can follow them.",
        "Saya akan dokumentasikan langkahnya supaya on-call berikutnya bisa ikut.",
        ["I'll document the steps", "so the next on-call", "can follow them"],
        ["I'll", "document", "the", "steps", "so", "the", "next", "on-call", "can", "follow", "them"],
        ["document", "on-call", "follow"],
        ["future_will", "purpose_so"],
        ["I will document the step so next on call can follow them"],
        "Close the loop after fixing an issue.",
        "Tutup loop setelah memperbaiki masalah.",
    ),
]


def write_file(name: str, title: str, title_id: str, items: list[dict]) -> None:
    data = {
        "id": name,
        "title": title,
        "titleId": title_id,
        "itemCount": len(items),
        "items": items,
    }
    path = OUT / f"{name}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.name} ({len(items)} items)")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    write_file("it-operations", "IT Operations", "Operasi IT", IT)
    write_file("reporting-supervisor", "Reporting to Supervisor", "Laporan ke Supervisor", REPORT)
    write_file("daily-office", "Daily Office Conversation", "Percakapan Kantor Harian", DAILY)
    write_file("meetings", "Meetings", "Meeting", MEET)
    write_file("problem-solving", "Problem Solving", "Pemecahan Masalah", PROBLEM)

    all_items = IT + REPORT + DAILY + MEET + PROBLEM
    manifest = {
        "version": "1.0.0",
        "itemCount": len(all_items),
        "packs": [
            {"id": "it-operations", "title": "IT Operations", "titleId": "Operasi IT", "itemCount": len(IT)},
            {
                "id": "reporting-supervisor",
                "title": "Reporting to Supervisor",
                "titleId": "Laporan ke Supervisor",
                "itemCount": len(REPORT),
            },
            {
                "id": "daily-office",
                "title": "Daily Office Conversation",
                "titleId": "Percakapan Kantor Harian",
                "itemCount": len(DAILY),
            },
            {"id": "meetings", "title": "Meetings", "titleId": "Meeting", "itemCount": len(MEET)},
            {
                "id": "problem-solving",
                "title": "Problem Solving",
                "titleId": "Pemecahan Masalah",
                "itemCount": len(PROBLEM),
            },
        ],
    }
    (OUT / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"manifest itemCount={len(all_items)}")


if __name__ == "__main__":
    main()
