#!/usr/bin/env python3
"""Generate rich workplace English exercise modules."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODULES = ROOT / "content" / "modules"
MANIFEST = ROOT / "content" / "manifest.json"

TTS = {"scenario": True, "prompt": True, "answer": True}


def mk(
    module_id: str,
    prefix: str,
    idx: int,
    difficulty: str,
    scenario: str,
    prompt: str,
    choices: list[str],
    correct: str,
    explanation: str,
    tags: list[str],
) -> dict:
    return {
        "id": f"{prefix}-{idx:02d}",
        "moduleId": module_id,
        "difficulty": difficulty,
        "scenario": scenario,
        "prompt": prompt,
        "choices": [
            {"key": k, "text": t} for k, t in zip(["A", "B", "C", "D"], choices)
        ],
        "correctKey": correct,
        "explanation": explanation,
        "tags": tags,
        "tts": TTS,
    }


def pack(
    module_id: str,
    title: str,
    description: str,
    persona: list[str],
    items: list[dict],
) -> dict:
    return {
        "id": module_id,
        "title": title,
        "description": description,
        "persona": persona,
        "status": "ready",
        "itemCount": len(items),
        "items": items,
    }


def write_module(data: dict) -> None:
    path = MODULES / f"{data['id']}.json"
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.name}: {data['itemCount']} items")


# ---------------------------------------------------------------------------
# Stub modules (12 each)
# ---------------------------------------------------------------------------

def interview_technical() -> dict:
    mid, p = "interview-technical", "tec"
    items = [
        mk(mid, p, 1, "mid",
           "An interviewer asks you to design a URL shortener that must survive sudden traffic spikes.",
           "Which answer best shows structured system-design thinking?",
           [
               "I would use a database and some servers.",
               "I would start with requirements: write/read ratio, latency target, and uniqueness. Then propose an API, a base62 ID generator, a primary store with caching, and a scale-out plan using partitioning and CDN for redirects.",
               "I once built something similar at home for fun.",
               "Kubernetes will solve the scaling automatically.",
           ], "B",
           "Strong answers frame requirements first, then components, then scaling — not vague tools.",
           ["system-design", "scalability"]),
        mk(mid, p, 2, "senior",
           "They ask: SQL vs NoSQL for an order history service with complex joins and strong consistency needs.",
           "What is the clearest tradeoff statement?",
           [
               "NoSQL is always faster so we should use it.",
               "Given multi-table joins and strong consistency, a relational store is a better default. NoSQL could help for high write throughput or flexible schemas, but we would pay in query complexity and consistency tradeoffs.",
               "I only use Postgres for everything.",
               "It does not matter as long as we use an ORM.",
           ], "B",
           "Interviewers want criteria-based tradeoffs tied to consistency and access patterns.",
           ["tradeoffs", "database"]),
        mk(mid, p, 3, "mid",
           "Explain CAP theorem in practical terms for a payments ledger.",
           "Which explanation is most interview-ready?",
           [
               "CAP means choose any two letters and move on.",
               "In a partition, a payments ledger should favor consistency over availability: better to reject or queue writes than accept conflicting balances. Availability can be recovered with retries and clear user messaging.",
               "We can ignore partitions in the cloud.",
               "Microservices remove CAP concerns.",
           ], "B",
           "Tie CAP to the domain: money systems usually prioritize consistency during partitions.",
           ["CAP", "payments"]),
        mk(mid, p, 4, "junior",
           "Walk through debugging a slow API endpoint.",
           "Which response shows a professional debug process?",
           [
               "I would restart the server first every time.",
               "I would reproduce with timing, check metrics and traces, identify whether the bottleneck is CPU, DB, or network, then validate a fix with before/after latency.",
               "I would rewrite the endpoint in another language.",
               "I would ask users to stop using that feature.",
           ], "B",
           "A clear debug narrative: reproduce → observe → localize → fix → verify.",
           ["debugging", "performance"]),
        mk(mid, p, 5, "senior",
           "How would you introduce rate limiting for a public API without breaking legitimate clients?",
           "Which answer is strongest?",
           [
               "Block everyone who exceeds one request per second.",
               "I would define per-client quotas, return standard 429 with Retry-After, start in shadow mode to measure impact, then enforce gradually with burst tokens for good actors and clear docs for clients.",
               "Just put Cloudflare in front and hope.",
               "Rate limiting is only for DDoS, not product APIs.",
           ], "B",
           "Show gradual rollout, client-friendly errors, and measurement before hard enforcement.",
           ["rate-limiting", "API"]),
        mk(mid, p, 6, "mid",
           "How do you decide between synchronous and asynchronous processing for invoice generation?",
           "What should you say?",
           [
               "Always async because it is modern.",
               "If the user needs the invoice immediately to continue, keep a synchronous path with a tight SLA. If generation can take longer, accept the request, enqueue work, and notify when ready — with idempotency keys to avoid duplicates.",
               "Use cron every night only.",
               "Let the frontend generate PDFs.",
           ], "B",
           "Map sync/async to user latency needs and reliability concerns like idempotency.",
           ["async", "reliability"]),
        mk(mid, p, 7, "senior",
           "Explain observability for a microservice fleet.",
           "Which answer is most complete?",
           [
               "We log everything to text files on each box.",
               "I want structured logs, metrics for SLIs, and distributed traces tied by request IDs — plus alerting on symptoms users feel, not only host CPU. Dashboards should answer what broke, where, and how bad.",
               "APM tools replace the need for design.",
               "If on-call is awake, observability is enough.",
           ], "B",
           "Logs + metrics + traces, user-centric SLIs, and actionable alerts.",
           ["observability", "SLI"]),
        mk(mid, p, 8, "mid",
           "Explain caching for a product catalog that updates a few times per hour.",
           "Which statement is best?",
           [
               "Cache forever to maximize hit rate.",
               "I would cache reads with a short TTL aligned to update frequency, use cache-aside, and invalidate on publish events. I would also define stale-while-revalidate behavior so brief staleness does not become wrong pricing.",
               "Never cache; databases are fast enough.",
               "Put the entire database in Redis.",
           ], "B",
           "Good caching answers include TTL, invalidation, and correctness boundaries.",
           ["caching", "correctness"]),
        mk(mid, p, 9, "junior",
           "What is idempotency and why does it matter in APIs?",
           "Which definition is clearest?",
           [
               "It means the API is very fast.",
               "Idempotency means repeating the same request does not create duplicate side effects. It matters for payments and retries so network failures do not double-charge or double-create resources.",
               "It means we use HTTPS.",
               "It is another word for authentication.",
           ], "B",
           "Simple definition plus why retries make it essential.",
           ["idempotency", "API"]),
        mk(mid, p, 10, "senior",
           "How would you migrate a monolith to services without a big-bang rewrite?",
           "Which approach sounds most senior?",
           [
               "Freeze all features and rewrite for six months.",
               "I would extract high-churn bounded contexts first behind stable APIs, use the strangler pattern, keep a shared data ownership plan, and measure latency and error budgets during each cutover.",
               "Copy the codebase into many repos on day one.",
               "Microservices first, product later.",
           ], "B",
           "Strangler pattern, bounded contexts, and risk-managed cutovers beat big-bang rewrites.",
           ["migration", "architecture"]),
        mk(mid, p, 11, "mid",
           "Walk me through securing secrets in a CI/CD pipeline.",
           "Best answer?",
           [
               "Commit .env files but do not push them.",
               "Store secrets in a vault or CI secret store, inject at runtime, rotate regularly, scope least privilege per pipeline, and never print secrets in logs. Pull requests should not expose production credentials.",
               "Email secrets to the team when needed.",
               "Hardcode secrets in the Dockerfile for convenience.",
           ], "B",
           "Vault/CI secrets, least privilege, rotation, and no secret leakage.",
           ["security", "CI/CD"]),
        mk(mid, p, 12, "senior",
           "How do you reason about SLOs for a checkout API?",
           "Which answer is strongest?",
           [
               "Aim for 100% uptime always.",
               "I would define an availability SLO on successful checkout completion, set an error budget, and use burn-rate alerts. Product and eng would agree what latency percentile matters for conversion, then prioritize reliability work when budget burns fast.",
               "SLOs are only for executives and not engineers.",
               "If monitoring is green, the SLO is fine.",
           ], "B",
           "SLOs need user outcomes, error budgets, and shared prioritization language.",
           ["SLO", "error-budget"]),
    ]
    return pack(mid, "Interview — Technical",
                "Tradeoffs, system design phrasing, and clear technical explanations.",
                ["SRE", "Fullstack"], items)


def offer_negotiation() -> dict:
    mid, p = "offer-negotiation", "off"
    items = [
        mk(mid, p, 1, "mid",
           "You received a written offer. Base salary is 10% below your target. You still want the role.",
           "Which counter is most professional?",
           [
               "This offer is insulting. Fix it.",
               "Thank you for the offer. I am excited about the role. Based on market data and my scope in reliability ownership, I am targeting X base. Is there flexibility to move closer to that number?",
               "I will only accept if you match my dream number today.",
               "Ignore the offer email for a week to create pressure.",
           ], "B",
           "Gratitude + enthusiasm + data-backed ask + collaborative question.",
           ["salary", "counter"]),
        mk(mid, p, 2, "junior",
           "Recruiter asks for your current salary before sharing a range.",
           "What is a strong reply?",
           [
               "I make very little, so anything is fine.",
               "I prefer to focus on the range for this role and the market. What budget range has been approved for this position?",
               "I refuse to talk numbers ever.",
               "Tell me the max and I will take it.",
           ], "B",
           "Redirect to role budget without oversharing or sounding hostile.",
           ["compensation", "range"]),
        mk(mid, p, 3, "mid",
           "The company cannot raise base much but offers a signing bonus and earlier equity refresh.",
           "How do you respond thoughtfully?",
           [
               "Base is all that matters; reject everything else.",
               "I appreciate the creative package. Could we confirm the signing bonus amount, vesting timing, and whether a six-month salary review is possible? I want the total package to reflect the scope.",
               "Fine, whatever.",
               "I need unlimited equity forever.",
           ], "B",
           "Evaluate total comp components and ask clarifying structure questions.",
           ["total-comp", "equity"]),
        mk(mid, p, 4, "senior",
           "You are negotiating an IT Manager offer and want clarity on team size and budget authority.",
           "Which ask belongs in negotiation?",
           [
               "Can I fire anyone in week one?",
               "Before I accept, I would like written clarity on team size, hiring plan for the next two quarters, and decision rights for tooling budget. That helps me commit to the outcomes we discussed.",
               "Titles do not matter; skip the details.",
               "I will figure out authority after I join.",
           ], "B",
           "Senior negotiation includes scope and authority, not only money.",
           ["scope", "management"]),
        mk(mid, p, 5, "junior",
           "They ask if you can start in one week. You need three weeks to hand over your current job.",
           "Best reply?",
           [
               "Sure, I will ghost my current employer.",
               "I can start on [date in three weeks]. I want to complete a clean handover at my current company. If helpful, I can do limited onboarding reading before day one.",
               "I might start someday.",
               "Take it or leave it: two months from now only.",
           ], "B",
           "Protect professionalism with a firm date and optional light prep.",
           ["start-date", "handover"]),
        mk(mid, p, 6, "mid",
           "Two offers are open. Company A is your preference but slower on paperwork.",
           "How do you buy time politely with Company B?",
           [
               "Lie and say you are sick.",
               "I am very interested and want to give this decision proper attention. Could I confirm by Friday? I will keep you updated if anything changes sooner.",
               "Tell them you already signed elsewhere.",
               "Stop answering emails.",
           ], "B",
           "Ask for a concrete extension without burning goodwill.",
           ["timeline", "multiple-offers"]),
        mk(mid, p, 7, "senior",
           "Remote policy is unclear in the offer letter.",
           "What should you clarify in writing?",
           [
               "I assume remote forever with no questions.",
               "Could we add the remote/hybrid expectation to the offer: work location, core collaboration hours, and travel frequency for onsite planning? I want alignment before signing.",
               "Policies always change, so skip it.",
               "Only ask after your first performance review.",
           ], "B",
           "Put location and travel expectations in writing before you accept.",
           ["remote", "expectations"]),
        mk(mid, p, 8, "mid",
           "HR says benefits are standard and not negotiable. You care about learning budget.",
           "How do you ask?",
           [
               "Standard is unacceptable.",
               "Understood on core benefits. Is there flexibility for an annual learning budget or conference stipend? Professional development is important for the SRE craft I will bring to the team.",
               "Forget benefits; only cash.",
               "Demand a company car.",
           ], "B",
           "Accept constraints, then ask for adjacent levers tied to role value.",
           ["benefits", "learning"]),
        mk(mid, p, 9, "junior",
           "You want to accept verbally but wait for the written offer.",
           "Best phrasing?",
           [
               "I accept; no need for paperwork.",
               "I am prepared to accept contingent on receiving the written offer that reflects what we discussed on base, start date, and title. Please send it over and I will sign promptly.",
               "Maybe I accept.",
               "Send me something eventually.",
           ], "B",
           "Show intent while anchoring on written terms.",
           ["accept", "written-offer"]),
        mk(mid, p, 10, "senior",
           "The offer includes a non-compete that seems broad for your region.",
           "Professional next step?",
           [
               "Sign quietly and ignore it.",
               "I am excited to move forward. Before signing, I would like to review the non-compete scope and duration with counsel and discuss a narrower version that still protects the company’s interests.",
               "Refuse all legal documents.",
               "Post the contract on social media for advice.",
           ], "B",
           "Stay collaborative while protecting yourself through review and scoped edits.",
           ["legal", "non-compete"]),
        mk(mid, p, 11, "mid",
           "Recruiter asks why you are countering.",
           "Strong rationale?",
           [
               "Because I can.",
               "Because the scope includes on-call leadership and cross-team delivery ownership. The counter aligns compensation with that responsibility and current market ranges for similar roles.",
               "Your first number was a test.",
               "My friend got more at another company, end of story.",
           ], "B",
           "Tie the counter to scope and market, not ego.",
           ["rationale", "market"]),
        mk(mid, p, 12, "mid",
           "You decide to decline an offer after negotiating.",
           "Which decline preserves the relationship?",
           [
               "Your offer was a joke.",
               "Thank you for the offer and the thoughtful process. After careful consideration I will not be moving forward. I have a lot of respect for the team and hope our paths cross again.",
               "No reply needed.",
               "Accept then resign in week one.",
           ], "B",
           "Decline with gratitude and leave the door open.",
           ["decline", "relationship"]),
    ]
    return pack(mid, "Offer & Negotiation",
                "Salary, start date, benefits, and polite counter-offers.",
                ["IT Manager", "SRE", "Fullstack"], items)


def standup_sync() -> dict:
    mid, p = "standup-sync", "stu"
    items = [
        mk(mid, p, 1, "junior",
           "Daily standup. Yesterday you finished auth middleware; today rate-limit tests; blocked on staging credentials.",
           "Best standup update?",
           [
               "Same as usual.",
               "Yesterday: finished auth middleware. Today: rate-limit tests. Blocker: need staging credentials from platform — ETA blocked until that lands.",
               "I did a lot of stuff and will do more stuff.",
               "No updates.",
           ], "B",
           "Yesterday / Today / Blocker is the classic clear format.",
           ["standup", "blocker"]),
        mk(mid, p, 2, "mid",
           "You will miss today's estimate because a flaky integration test ate your morning.",
           "How do you say it in standup?",
           [
               "Tests are stupid.",
               "I am slipping half a day because flaky payment tests blocked local verification. I am quarantining the flake and will still open the PR by end of day tomorrow unless the flake returns.",
               "Everything is fine.",
               "I might be done sometime.",
           ], "B",
           "Name impact, mitigation, and a revised ETA.",
           ["ETA", "transparency"]),
        mk(mid, p, 3, "mid",
           "You need help from a teammate who is mid-focus.",
           "Best ask in standup?",
           [
               "Someone help me now.",
               "I need 20 minutes with Alex after standup to pair on the Redis lock bug. Without that, my ETA moves from today to tomorrow.",
               "I will figure it out alone forever.",
               "Alex always ignores me.",
           ], "B",
           "Specific person, timebox, and consequence if help is delayed.",
           ["ask-for-help", "pairing"]),
        mk(mid, p, 4, "senior",
           "As tech lead, two people are blocked on the same API contract.",
           "What do you say to unblock the team?",
           [
               "Discuss it later somehow.",
               "Let's take the API contract offline for ten minutes after standup — Mira and Jordan with me. Goal: decide request shape so both streams can continue today.",
               "Everyone wait until next sprint.",
               "Build whatever you want independently.",
           ], "B",
           "Leaders convert shared blockers into a timeboxed decision forum.",
           ["facilitation", "leadership"]),
        mk(mid, p, 5, "junior",
           "You have no blocker but expect one later when QA starts.",
           "Good proactive update?",
           [
               "No blockers, nothing to say.",
               "No blocker now. Heads-up: I will need QA support this afternoon for the checkout edge cases. I will book a slot in the QA channel after standup.",
               "QA will magically appear.",
               "Blockers are only for emergencies.",
           ], "B",
           "Flag upcoming dependencies early so others can plan.",
           ["proactive", "dependency"]),
        mk(mid, p, 6, "mid",
           "Standup is drifting into a long design debate.",
           "What should you say?",
           [
               "Let us debate for the full hour.",
               "This is useful but bigger than standup. Parking it for a 15-minute design huddle at 11:00 — I will post notes. Back to blockers for everyone else.",
               "Stop talking, all of you.",
               "Cancel standup forever.",
           ], "B",
           "Protect standup time; park deep topics with an owner and time.",
           ["facilitation", "parking-lot"]),
        mk(mid, p, 7, "mid",
           "You finished early and can take overflow work.",
           "How do you offer help?",
           [
               "I am bored.",
               "I have capacity after lunch. If anyone is at risk on the release checklist, I can take a verification task — drop it in the thread.",
               "Do not give me more work.",
               "I will silently refactor unrelated code.",
           ], "B",
           "Offer capacity with a clear channel and useful target.",
           ["capacity", "teamwork"]),
        mk(mid, p, 8, "senior",
           "A junior says 'still working on it' with no detail for three days.",
           "As lead, what do you ask?",
           [
               "Why are you so slow?",
               "Can you break that into what is done, what is left, and where you are stuck? Even a rough percentage helps us unblock you today.",
               "Fine, keep going silently.",
               "I will reassign without asking.",
           ], "B",
           "Coach for visibility without public shaming.",
           ["coaching", "visibility"]),
        mk(mid, p, 9, "junior",
           "Remote sync: your audio failed and you missed half the updates.",
           "Best recovery message in chat?",
           [
               "Whatever.",
               "Sorry, I dropped audio. Could someone paste the action items and owners in the thread? I will confirm my items in two minutes.",
               "Pretend you heard everything.",
               "Demand a full restart of the meeting.",
           ], "B",
           "Own the drop, ask for written actions, confirm quickly.",
           ["remote", "recovery"]),
        mk(mid, p, 10, "mid",
           "You discovered a production risk while preparing standup notes.",
           "How do you raise it without derailing?",
           [
               "Scream incident in standup.",
               "Quick risk flag: error rate on login is trending up 2x since last night. I will open a war-room thread after standup; not a full SEV yet. Continuing with other updates now.",
               "Keep it secret until it burns.",
               "Blame yesterday's on-call in public.",
           ], "B",
           "Signal risk, next channel, and keep standup moving.",
           ["risk", "production"]),
        mk(mid, p, 11, "mid",
           "Cross-timezone teammate cannot attend live standup.",
           "Best async substitute?",
           [
               "They will catch up somehow.",
               "I posted an async standup in the channel with yesterday/today/blockers and tagged owners. Please reply in-thread before 10:00 your time so we do not wait on the live call.",
               "Skip them permanently.",
               "Only voice notes, no text.",
           ], "B",
           "Async standup needs structure, tags, and a reply deadline.",
           ["async", "timezone"]),
        mk(mid, p, 12, "senior",
           "Sprint goal is at risk. Standup reveals three parallel blockers.",
           "Lead summary to close standup?",
           [
               "Good luck everyone.",
               "Summary: sprint goal at risk from API, flaky tests, and QA bandwidth. Owners: me on API decision at 11:00, Sam on flake quarantine, Priya on QA slotting. We reconvene at 4pm with go/no-go for Thursday release.",
               "We will see what happens.",
               "Cancel the release quietly.",
           ], "B",
           "Close with owners, times, and a decision checkpoint.",
           ["summary", "decision"]),
    ]
    return pack(mid, "Standup & Sync",
                "Blockers, ETA, and asking for help without drama.",
                ["SRE", "Fullstack"], items)


def slack_email() -> dict:
    mid, p = "slack-email", "slk"
    items = [
        mk(mid, p, 1, "junior",
           "You need a review on a PR that blocks release today.",
           "Best Slack message?",
           [
               "Can someone review???",
               "Hi team — need a review on PR #482 (auth rate limit) by 3pm to keep today's release. ~15 min review. Prefer: Jordan or Mira. Link and test notes in the PR.",
               "Review this when you can someday.",
               "@channel PLEASE HELP NOW!!!!!!!!",
           ], "B",
           "Clear ask, deadline, effort estimate, preferred reviewers, link.",
           ["slack", "ask", "PR"]),
        mk(mid, p, 2, "mid",
           "A stakeholder emailed a vague request: 'Can you improve the dashboard?'",
           "Best clarifying reply?",
           [
               "Sure, I will redesign everything.",
               "Happy to help. To scope this well: which metrics matter most, who is the primary audience, and is this for this quarter or exploratory? A 15-minute call tomorrow would help me propose options.",
               "That request is too vague; rejected.",
               "I already started building without asking.",
           ], "B",
           "Clarify outcome, audience, and timeline before building.",
           ["email", "clarification", "scope"]),
        mk(mid, p, 3, "mid",
           "You must decline a meeting invite that conflicts with an incident review.",
           "Professional decline?",
           [
               "Busy. No.",
               "I cannot make this time due to a scheduled incident review. Please share notes or a recording, and I can async-comment by EOD. Happy to join a follow-up if decisions remain.",
               "Ignore the invite.",
               "Accept then do not show up.",
           ], "B",
           "Decline with reason, offer async path, stay available for decisions.",
           ["calendar", "decline"]),
        mk(mid, p, 4, "senior",
           "You need to escalate a delayed dependency without blaming the other team in Slack.",
           "Best thread message?",
           [
               "Payments team is blocking us again as usual.",
               "Status: checkout release is blocked on Payments API contract (ticket PAY-221). Impact: we miss Thursday if unresolved. Ask: can we confirm owner and ETA by noon? Happy to pair for 30 minutes today.",
               "CC the CEO immediately.",
               "We will ship without the dependency and hope.",
           ], "B",
           "Impact + ask + offer to help beats public blame.",
           ["escalation", "cross-team", "tone"]),
        mk(mid, p, 5, "junior",
           "You accidentally sent a half-finished message to a large channel.",
           "Best recovery?",
           [
               "Delete and pretend nothing happened.",
               "Sorry — sent too early. Please ignore the incomplete note. Full update with owners and ETA coming in five minutes.",
               "Leave it and never clarify.",
               "Blame Slack for auto-send.",
           ], "B",
           "Quick acknowledgment + corrected follow-up restores trust.",
           ["recovery", "slack"]),
        mk(mid, p, 6, "mid",
           "Write a concise status email to your manager after a partial outage.",
           "Which version is best?",
           [
               "Things broke then got better.",
               "Subject: Checkout degradation — restored. Impact: 22 minutes, ~8% failed checkouts. Cause: bad feature flag default. Mitigation: flag disabled at 14:12. Follow-ups: canary checks + flag review due Friday. Full timeline in the incident doc.",
               "Please see Slack for 200 messages.",
               "Not our fault; vendor issue; no details.",
           ], "B",
           "Subject + impact + cause + mitigation + dated follow-ups.",
           ["email", "status", "incident"]),
        mk(mid, p, 7, "senior",
           "A heated Slack thread is going off-topic and personal.",
           "How do you reset it?",
           [
               "Keep arguing in public.",
               "Let's pause the thread. The decision we need is X by tomorrow. I'll schedule a 20-minute call for stakeholders and summarize the options in a doc. Please keep feedback focused on the proposal.",
               "Lock the channel forever.",
               "Mock the loudest person.",
           ], "B",
           "De-escalate, restate the decision, move to a better forum.",
           ["facilitation", "conflict", "slack"]),
        mk(mid, p, 8, "mid",
           "You want feedback on an RFC before Friday.",
           "Best async ask?",
           [
               "Thoughts?",
               "RFC: read-replica cutover (doc linked). Ask: please comment on risk section and rollback plan by Thursday 4pm. Silent assent after that means we proceed with the proposed option B.",
               "Approve immediately without reading.",
               "Ping everyone every hour until they reply.",
           ], "B",
           "Doc link, specific ask, deadline, and default if silent.",
           ["RFC", "async", "deadline"]),
        mk(mid, p, 9, "junior",
           "Customer success asks in Slack if a bug is 'fixed for sure'.",
           "Accurate reply?",
           [
               "Yes 100% forever.",
               "Fix is deployed to production and error rate is back to baseline for 45 minutes. We will keep watching through peak traffic today and confirm final status at 6pm.",
               "Probably fine, do not worry.",
               "Tell customers it never happened.",
           ], "B",
           "State evidence and monitoring window; avoid absolute guarantees.",
           ["customer", "confidence"]),
        mk(mid, p, 10, "mid",
           "You need to nudge a stalled email thread with an external vendor.",
           "Best follow-up?",
           [
               "Hello??? Still waiting!!!!",
               "Following up on my note from Tuesday about the sandbox credentials. Could you confirm ETA by Friday? Our integration test window is next Monday and we need access two days prior.",
               "CC their CEO on the first follow-up.",
               "Threaten to cancel without context.",
           ], "B",
           "Reference prior ask, give a deadline, explain business reason.",
           ["vendor", "follow-up", "email"]),
        mk(mid, p, 11, "senior",
           "Announce a breaking API change to partner engineers.",
           "Clearest message structure?",
           [
               "API changing soon. Good luck.",
               "Breaking change on /v2/orders on June 15: field `status` becomes enum. Why: consistency across services. Action: update clients before June 10. Migration guide and examples linked. Questions: reply in this thread or office hours Thursday 3pm.",
               "Read the entire changelog dump with no summary.",
               "Ship breakages without notice to move faster.",
           ], "B",
           "What/when/why/action/support channel — partner-friendly.",
           ["API", "announcement", "partners"]),
        mk(mid, p, 12, "mid",
           "You disagree with a peer's proposal in a public channel.",
           "How do you disagree well?",
           [
               "This idea is terrible.",
               "Thanks for drafting this. I see risk in approach A around retry storms. Have we considered approach B with idempotency keys? Happy to sketch a quick comparison table if useful.",
               "Agree publicly then block privately.",
               "React with eyes emoji only.",
           ], "B",
           "Appreciate, name the risk, offer an alternative, invite collaboration.",
           ["disagreement", "tone", "collaboration"]),
    ]
    return pack(mid, "Slack & Email",
                "Clear asks, tone control, and async thread etiquette.",
                ["IT Manager", "SRE", "Fullstack"], items)


def presentation_demo() -> dict:
    mid, p = "presentation-demo", "pre"
    items = [
        mk(mid, p, 1, "mid",
           "You open a demo of the new incident dashboard for leadership.",
           "Best opening line?",
           [
               "Um, so yeah, this is a thing we built.",
               "In the next ten minutes I will show how this dashboard cuts mean time to detect from minutes to seconds, then walk through one live incident scenario and take questions.",
               "Let me start with my life story.",
               "Please read the slides; I will stay quiet.",
           ], "B",
           "Agenda + outcome + timebox builds executive attention.",
           ["opening", "demo"]),
        mk(mid, p, 2, "junior",
           "The demo environment is slow. Stakeholders are waiting.",
           "What do you say?",
           [
               "This always happens; not my fault.",
               "The staging environment is slower than production right now. I will narrate the flow with screenshots while it loads, then switch to the live view for the final step.",
               "Cancel the meeting immediately.",
               "Sit in silence until it works.",
           ], "B",
           "Acknowledge, keep value flowing, recover to live when possible.",
           ["recovery", "demo"]),
        mk(mid, p, 3, "senior",
           "A VP interrupts: 'Why should we fund this?'",
           "Strong bridge answer?",
           [
               "Because engineers like shiny tools.",
               "Great question — the business case is fewer prolonged outages. Last quarter we lost an estimated $X in failed checkouts during slow detection. This investment targets that loss with a measurable MTTD reduction.",
               "I will answer later maybe.",
               "Please wait until the end of all thirty slides.",
           ], "B",
           "Translate tech into business impact with evidence.",
           ["executive", "business-case"]),
        mk(mid, p, 4, "mid",
           "Transition from architecture slide to live demo.",
           "Best transition phrase?",
           [
               "Moving on randomly.",
               "That was the design. Now I will show the same flow live: detect anomaly, open runbook, and page the right owner in under a minute.",
               "Forget the architecture; it was wrong.",
               "Any questions on everything at once forever?",
           ], "B",
           "Explicit bridge that previews what viewers will see.",
           ["transition", "demo"]),
        mk(mid, p, 5, "mid",
           "Someone asks a question outside the demo scope.",
           "How do you handle it?",
           [
               "That is irrelevant.",
               "Good question — it is adjacent but outside today's scope. I will park it on the parking-lot slide and follow up with a short note after this session so we stay on the detection flow.",
               "Answer for twenty minutes and lose the agenda.",
               "Pretend you did not hear it.",
           ], "B",
           "Validate, park, protect the agenda, promise follow-up.",
           ["Q&A", "facilitation"]),
        mk(mid, p, 6, "junior",
           "You do not know the answer to a technical question in Q&A.",
           "Best response?",
           [
               "Invent a confident wrong answer.",
               "I do not want to guess on that detail. I will confirm with the owning engineer and send the accurate answer to this group within one business day.",
               "Say nothing and look at your laptop.",
               "Change the topic abruptly.",
           ], "B",
           "Honesty + ownership of follow-up beats bluffing.",
           ["Q&A", "integrity"]),
        mk(mid, p, 7, "senior",
           "Close a roadmap presentation to directors.",
           "Strong closing?",
           [
               "That is all. Bye.",
               "To summarize: three investments, one dependency on platform capacity, and a decision needed on the June canary. I recommend we approve option B today. I will send the one-pager and decision log within an hour.",
               "Any random thoughts?",
               "We will somehow figure it out later.",
           ], "B",
           "Summary + decision ask + concrete follow-up artifact.",
           ["closing", "decision"]),
        mk(mid, p, 8, "mid",
           "A skeptical engineer challenges your latency numbers mid-demo.",
           "Professional handling?",
           [
               "You are wrong and loud.",
               "Appreciate the challenge. These numbers are p95 from last week's production sample — source linked on slide 4. If you have a conflicting dataset, send it after and we will reconcile.",
               "Delete the slide live in panic.",
               "Agree the numbers are fake.",
           ], "B",
           "Welcome scrutiny, cite source, offer post-meeting reconciliation.",
           ["challenge", "data"]),
        mk(mid, p, 9, "junior",
           "You are co-presenting and your partner freezes.",
           "What do you say?",
           [
               "Wow, awkward.",
               "I can take this section — we are at the rollout plan. After the demo we will cover owners and dates, then open Q&A.",
               "Stare at them until they recover.",
               "End the meeting without notice.",
           ], "B",
           "Smoothly take the baton and restate where you are.",
           ["co-present", "recovery"]),
        mk(mid, p, 10, "mid",
           "Hybrid meeting: remote attendees cannot see your shared screen clearly.",
           "What should you do?",
           [
               "Ignore remotes; room matters more.",
               "Remote folks — confirming you can see the dashboard shared window. I will zoom the critical panel and narrate clicks so audio-only participants can follow.",
               "Tell remotes to figure it out.",
               "Stop sharing and only talk.",
           ], "B",
           "Check inclusion, adjust visuals, narrate for audio-only.",
           ["hybrid", "inclusion"]),
        mk(mid, p, 11, "senior",
           "Product asks you to 'make it exciting' for a customer webinar.",
           "Professional framing?",
           [
               "Use hype words and hide limitations.",
               "We can keep it customer-exciting and accurate: lead with the outcome they care about, show one crisp workflow, and be explicit about current limits and roadmap timing.",
               "Refuse to present to customers.",
               "Read the internal RFC verbatim.",
           ], "B",
           "Excitement without overselling; clarity on limits builds trust.",
           ["customer", "webinar"]),
        mk(mid, p, 12, "mid",
           "You have two minutes left and three slides remaining.",
           "Best move?",
           [
               "Speed-read every bullet incomprehensibly.",
               "I will skip the deep-dive slides and land on the decision ask and next steps. Deep-dive appendix is in the leave-behind.",
               "Run overtime without asking.",
               "Abruptly stop mid-sentence.",
           ], "B",
           "Protect the decision moment; park detail in appendix.",
           ["timeboxing", "closing"]),
    ]
    return pack(mid, "Presentation & Demo",
                "Openings, transitions, and handling Q&A under pressure.",
                ["IT Manager", "Fullstack"], items)


def pr_code_review() -> dict:
    mid, p = "pr-code-review", "prc"
    items = [
        mk(mid, p, 1, "mid",
           "A teammate's PR lacks tests for a payment edge case.",
           "Best review comment?",
           [
               "This is careless work.",
               "Thanks for the change. Could we add a test for the duplicate webhook case? Without it we risk double-charging on retries. Happy to sketch a fixture if useful.",
               "LGTM with no comments.",
               "Rewrite the entire PR in my style.",
           ], "B",
           "Specific risk + concrete ask + offer to help.",
           ["review", "tests", "tone"]),
        mk(mid, p, 2, "junior",
           "You disagree with a naming choice that is not blocking.",
           "How do you phrase it?",
           [
               "Rename everything or I will block.",
               "Non-blocking nit: `processStuff` is vague. `processRefundWebhook` would help future readers. Approving either way.",
               "Ignore readability forever.",
               "Demand a 40-comment style fight.",
           ], "B",
           "Label nits as non-blocking and still approve when appropriate.",
           ["nit", "naming"]),
        mk(mid, p, 3, "senior",
           "PR introduces a risky migration without a rollback plan.",
           "Strong blocking comment?",
           [
               "No.",
               "Blocking: this migration needs a documented rollback and a expand/contract sequence. Can we split expand first, deploy readers, then contract? I want us safe if we must revert mid-rollout.",
               "Ship it Friday night.",
               "Approve to be nice.",
           ], "B",
           "Block on safety with a clearer safer sequence.",
           ["migration", "blocking"]),
        mk(mid, p, 4, "mid",
           "Author asks why you requested changes on performance.",
           "Clear explanation?",
           [
               "Because I said so.",
               "The N+1 query in the loop will amplify under peak checkout. A single batched fetch should keep p95 stable. Happy to pair for 15 minutes if the refactor is unclear.",
               "Performance never matters.",
               "Use microservices to hide it.",
           ], "B",
           "Explain impact quantitatively and offer pairing.",
           ["performance", "explanation"]),
        mk(mid, p, 5, "junior",
           "You made a mistake in a review comment.",
           "Best follow-up?",
           [
               "Leave the wrong comment forever.",
               "Correction: I misread the caching layer — your approach is fine. Sorry for the noise. Remaining ask is only the retry test.",
               "Double down to save face.",
               "Delete the PR.",
           ], "B",
           "Own the misread quickly; keep remaining asks crisp.",
           ["humility", "review"]),
        mk(mid, p, 6, "mid",
           "Security finds a secret logged in debug output inside the PR.",
           "How do you communicate urgency?",
           [
               "lol secrets.",
               "Blocking security issue: a token is logged in debug output. Please remove it, rotate the credential, and add a lint/check so we do not regress. I can help verify in staging after.",
               "Mention it casually next sprint.",
               "Merge first, fix later quietly.",
           ], "B",
           "Security blocks need clear action: remove, rotate, prevent.",
           ["security", "secrets"]),
        mk(mid, p, 7, "senior",
           "Two reviewers give conflicting guidance on architecture.",
           "As lead, what do you post?",
           [
               "Fight it out in comments for days.",
               "Thanks both. Decision: we will keep the module boundary as in option A for this PR, and open a follow-up RFC for the broader extract. Unblocking author now with that direction.",
               "Tell the author to guess.",
               "Close the PR out of frustration.",
           ], "B",
           "Make a decision, unblock, and park larger debate properly.",
           ["decision", "leadership"]),
        mk(mid, p, 8, "mid",
           "You want to praise a particularly good abstraction in a PR.",
           "Effective praise?",
           [
               "cool",
               "Nice work on the retry helper — the jitter and idempotency key handling will prevent a class of production incidents. Thanks for documenting the failure modes in the PR body.",
               "Finally someone competent.",
               "Praise only in private so others do not learn.",
           ], "B",
           "Specific praise reinforces the behaviors you want repeated.",
           ["praise", "culture"]),
        mk(mid, p, 9, "junior",
           "PR description is empty.",
           "Helpful request?",
           [
               "Write a novel.",
               "Could you add a short PR description: problem, approach, risk, and how you tested? It will speed up review and help on-call later.",
               "Approve without reading.",
               "Reject for style alone.",
           ], "B",
           "Ask for the minimum useful context, not bureaucracy.",
           ["PR-description", "process"]),
        mk(mid, p, 10, "mid",
           "A large PR mixes refactor and feature.",
           "Best guidance?",
           [
               "I love giant PRs.",
               "This will be easier and safer as two PRs: pure refactor first, then the feature on top. Reviewers can validate behavior changes without noise. Can we split before deeper review?",
               "Demand a full rewrite in one shot.",
               "Rubber-stamp to clear the queue.",
           ], "B",
           "Split for reviewability and safer rollback.",
           ["pr-size", "process"]),
        mk(mid, p, 11, "senior",
           "Junior author seems discouraged after many comments.",
           "Supportive message?",
           [
               "Maybe this job is not for you.",
               "Lots of comments here because the area is high risk, not because the work lacks value. The core approach is solid. Let's pair for 25 minutes to close the remaining two items together.",
               "Remove all comments to be nice.",
               "Silence them publicly.",
           ], "B",
           "Separate rigor from identity; offer concrete support.",
           ["mentoring", "tone"]),
        mk(mid, p, 12, "mid",
           "You approve after requested changes.",
           "Clear approval note?",
           [
               "ok",
               "Looks good now — retry tests cover the duplicate webhook path and rollback notes are clear. Approved. Please squash-merge after CI is green.",
               "Approved but I still hate it.",
               "Approve then immediately request changes again.",
           ], "B",
           "Confirm what improved and the merge condition.",
           ["approval", "clarity"]),
    ]
    return pack(mid, "PR & Code Review",
                "Soft/hard feedback and constructive suggestions.",
                ["Fullstack", "SRE"], items)


def postmortem() -> dict:
    mid, p = "postmortem", "pom"
    items = [
        mk(mid, p, 1, "mid",
           "You are drafting the incident summary for a SEV-1 checkout outage.",
           "Best blameless opening?",
           [
               "An engineer messed up the config again.",
               "On March 12, checkout errors rose to 18% for 47 minutes after a feature flag default changed. Customer impact was failed payments. We mitigated by disabling the flag and restored baseline.",
               "We do not know and will never know.",
               "This was inevitable so no analysis is needed.",
           ], "B",
           "Facts, impact, mitigation — no personal blame.",
           ["blameless", "summary"]),
        mk(mid, p, 2, "senior",
           "Leadership asks 'who caused it?' in the postmortem meeting.",
           "How do you redirect?",
           [
               "Name the person publicly.",
               "Our focus is the conditions that allowed this to reach production — detection gaps, review checks, and rollout controls — so we prevent recurrence. Individuals followed the process we had at the time.",
               "Refuse to write any document.",
               "Say it was random chance only.",
           ], "B",
           "Redirect from person to system conditions and prevention.",
           ["facilitation", "blameless"]),
        mk(mid, p, 3, "mid",
           "Write a clear contributing-factor statement.",
           "Which is strongest?",
           [
               "Bad luck.",
               "Contributing factors: flag defaults were not reviewed in change checklist; canary did not cover checkout path; alert threshold was too slow for revenue impact.",
               "People were careless.",
               "Cloud provider hate us.",
           ], "B",
           "Multiple systemic factors beat single-person narratives.",
           ["contributing-factors"]),
        mk(mid, p, 4, "junior",
           "Propose an action item after a missed alert.",
           "Best action item phrasing?",
           [
               "Be more careful.",
               "Action: add burn-rate alert on checkout success SLO, owner: Avery, due: March 20, success metric: alert fires within 5 minutes in staging game-day.",
               "Monitor harder somehow.",
               "Buy more tools immediately without owners.",
           ], "B",
           "Action items need owner, due date, and success criteria.",
           ["action-items", "SMART"]),
        mk(mid, p, 5, "mid",
           "Timeline section is messy with conflicting times.",
           "How do you fix communication?",
           [
               "Pick random times.",
               "I reconciled timeline stamps to UTC from pager, deploy, and chat logs. Please review the linked sheet; call out any missing events before we publish.",
               "Delete the timeline.",
               "Use local timezones mixed without labels.",
           ], "B",
           "One timezone, sourced logs, invite corrections before publish.",
           ["timeline", "accuracy"]),
        mk(mid, p, 6, "senior",
           "A customer asks for a public statement derived from the postmortem.",
           "Appropriate external language?",
           [
               "Our junior broke payments.",
               "We experienced a checkout disruption on March 12. We restored service the same day and are implementing additional safeguards around configuration changes and faster detection. We apologize for the impact.",
               "Share the full internal blame list.",
               "Deny any disruption occurred.",
           ], "B",
           "External notes: impact, restore, safeguards, apology — no internal blame.",
           ["customer", "external"]),
        mk(mid, p, 7, "mid",
           "Someone wants 30 action items from one incident.",
           "How do you prioritize in the room?",
           [
               "Accept all ideas equally.",
               "Let's prioritize the top three actions that most reduce recurrence probability: detection, safer defaults, and canary coverage. Other ideas go to the backlog with owners if capacity appears.",
               "Do nothing because lists are hard.",
               "Assign everything to the intern.",
           ], "B",
           "Focus on high-leverage actions; park the rest.",
           ["prioritization", "facilitation"]),
        mk(mid, p, 8, "junior",
           "You need to state what went well without sounding defensive.",
           "Good phrasing?",
           [
               "Actually we were perfect.",
               "What went well: on-call joined within two minutes, rollback was executed cleanly, and customer status updates went out every 15 minutes.",
               "Nothing went well; only pain.",
               "Praise only leadership.",
           ], "B",
           "Balanced postmortems include effective responses as learning too.",
           ["what-went-well"]),
        mk(mid, p, 9, "senior",
           "Legal asks you to soften speculative language.",
           "Professional edit?",
           [
               "Keep dramatic claims for effect.",
               "I replaced speculative phrases with verified facts and labeled hypotheses clearly as hypotheses pending confirmation. The prevention actions remain unchanged.",
               "Delete the whole postmortem.",
               "Ignore legal entirely.",
           ], "B",
           "Separate facts from hypotheses; keep prevention intact.",
           ["legal", "precision"]),
        mk(mid, p, 10, "mid",
           "Follow-up meeting: two action items are overdue.",
           "Best status prompt?",
           [
               "Why are you failing?",
               "Two actions are past due: canary coverage and flag checklist. Owners — can you share blockers and a new date today? If capacity is the issue, we will renegotiate scope with leadership.",
               "Quietly mark them done.",
               "Shame owners in a company-wide email.",
           ], "B",
           "Surface overdue work with blocker ask and escalation path.",
           ["follow-up", "accountability"]),
        mk(mid, p, 11, "mid",
           "Root cause is still uncertain after investigation.",
           "Honest wording?",
           [
               "Declare a scapegoat cause.",
               "Primary trigger is confirmed as the flag default. Deeper why around review process gaps is supported by evidence; a secondary hypothesis on cache stampede remains under investigation and will be updated by Friday.",
               "Pretend certainty.",
               "Say root cause is impossible.",
           ], "B",
           "Separate confirmed vs hypothesized causes with update timing.",
           ["uncertainty", "integrity"]),
        mk(mid, p, 12, "senior",
           "Close the postmortem review meeting.",
           "Strong closing?",
           [
               "Meeting over.",
               "We aligned on three actions with owners and dates. I will publish the final doc today, open tracking tickets, and schedule a 30-day effectiveness check. Thanks everyone for the blameless discussion.",
               "Add twenty more actions first.",
               "Leave without notes.",
           ], "B",
           "Confirm actions, publishing, tracking, and a check-back.",
           ["closing", "process"]),
    ]
    return pack(mid, "Postmortem",
                "Blameless language and clear action items.",
                ["SRE", "IT Manager"], items)


def cross_team() -> dict:
    mid, p = "cross-team", "xte"
    items = [
        mk(mid, p, 1, "mid",
           "Another team missed an agreed API delivery date that your release depends on.",
           "Best first message?",
           [
               "You broke our release again.",
               "Checking in on the Payments API date we aligned last Thursday. Our checkout release is gated on it. Can you share a revised ETA and whether a temporary stub is viable so we protect customer launch?",
               "Escalate to executives immediately with no context.",
               "Silently slip your date and surprise everyone later.",
           ], "B",
           "Reference the agreement, state impact, ask ETA and mitigation options.",
           ["dependency", "alignment"]),
        mk(mid, p, 2, "senior",
           "Vendor support is slow during a production degradation.",
           "Professional escalation email?",
           [
               "Your product is garbage.",
               "We are seeing elevated timeouts on gateway X since 13:40 UTC impacting checkout. Severity: high. Please confirm ticket priority and provide an ETA for an update within 30 minutes. Bridge link included.",
               "Wait silently for 24 hours.",
               "Tweet at their CEO first.",
           ], "B",
           "Impact, severity, ask, time expectation, and contact path.",
           ["vendor", "escalation"]),
        mk(mid, p, 3, "mid",
           "Security team rejected your change without clear next steps.",
           "How do you respond?",
           [
               "Security always blocks innovation.",
               "Thanks for the review. Could you list the specific controls we must satisfy to get to approve? I can propose compensating controls today if the original path is blocked for this release train.",
               "Bypass security in production.",
               "Abandon the project immediately.",
           ], "B",
           "Ask for concrete acceptance criteria and offer alternatives.",
           ["security", "unblock"]),
        mk(mid, p, 4, "junior",
           "You need design input from UX but they are overloaded.",
           "Polite ask?",
           [
               "Drop everything for me.",
               "I know bandwidth is tight. Could I get a 20-minute UX sanity check on the empty-state copy by Wednesday? If that is impossible, I will ship with the interim copy and schedule a polish pass next sprint.",
               "Ship ugly UI without notice forever.",
               "Complaint to their manager first.",
           ], "B",
           "Timebox, deadline, and fallback plan respect constraints.",
           ["ask", "ux", "priority"]),
        mk(mid, p, 5, "senior",
           "Two directors disagree on roadmap sequencing in a shared forum.",
           "How do you facilitate?",
           [
               "Pick a side loudly.",
               "I hear two priorities: reliability hardening vs partner launch. To decide, can we compare customer impact and opportunity cost for the next six weeks? I can bring a one-page tradeoff matrix by tomorrow morning.",
               "Let the argument run for an hour.",
               "Cancel both initiatives.",
           ], "B",
           "Reframe conflict into a decision artifact with criteria.",
           ["facilitation", "tradeoffs"]),
        mk(mid, p, 6, "mid",
           "Partner asks for an unrealistic same-day integration.",
           "Polite pushback?",
           [
               "Impossible. No.",
               "I want to support the launch. Same-day full integration is high risk given testing needs. We can deliver a read-only pilot today and the write path on Thursday after verification — does that meet the customer moment?",
               "Agree then fail silently.",
               "Ignore the partner email.",
           ], "B",
           "Offer a safer alternative that still helps the business moment.",
           ["pushback", "partner"]),
        mk(mid, p, 7, "mid",
           "Finance disputes a tooling purchase you need for on-call.",
           "Business-framed reply?",
           [
               "Engineers deserve nice toys.",
               "Understood on cost control. The tool reduces MTTR and pages; estimated savings exceed subscription within two incidents avoided. I attached a 30-day pilot plan with success metrics — can we approve the pilot?",
               "Buy it on a personal card secretly.",
               "Threaten resignation over the tool.",
           ], "B",
           "ROI + pilot + metrics speaks Finance's language.",
           ["finance", "business-case"]),
        mk(mid, p, 8, "junior",
           "You joined a cross-team kickoff and roles are unclear.",
           "Useful clarifying question?",
           [
               "Who is in charge of everything forever?",
               "To avoid gaps: who is the decision owner for API contract changes, and who is consulted vs informed? I can draft an RACI after this call if helpful.",
               "Stay confused silently.",
               "Assume you own all decisions.",
           ], "B",
           "Clarify decision rights early; offer to document RACI.",
           ["RACI", "kickoff"]),
        mk(mid, p, 9, "senior",
           "A peer manager's team keeps breaking shared SLOs.",
           "Constructive 1:1 opener with that manager?",
           [
               "Your team is the problem.",
               "I want us to succeed on the shared checkout SLO. Over the last month, error-budget burn from service B is the main driver. Can we align on ownership for two reliability fixes this sprint?",
               "Complain only to executives first.",
               "Add sarcasm in the shared channel.",
           ], "B",
           "Shared goal + data + concrete ask for joint ownership.",
           ["SLO", "peer-manager"]),
        mk(mid, p, 10, "mid",
           "Legal needs more time; sales wants to announce a feature.",
           "Alignment message?",
           [
               "Ship the announcement anyway.",
               "Sales wants to announce Friday; Legal needs through Monday for review. Proposal: soft-announce to design partners under NDA Friday, public announce Tuesday after Legal sign-off. Any objections by noon?",
               "Let teams fight in email forever.",
               "Cancel the feature.",
           ], "B",
           "Propose a sequenced compromise with a clear objection window.",
           ["legal", "sales", "compromise"]),
        mk(mid, p, 11, "mid",
           "Offshore vendor delivered incomplete work near deadline.",
           "Firm but professional note?",
           [
               "You failed us.",
               "The deliverable is missing load-test results and rollback steps listed in SOW section 4. Please confirm completion ETA by tomorrow 10:00 and whether you need clarification. Our go-live depends on those artifacts.",
               "Accept incomplete work silently.",
               "Publicly shame the vendor on LinkedIn.",
           ], "B",
           "Cite contract expectations, ask ETA, keep tone factual.",
           ["vendor", "SOW"]),
        mk(mid, p, 12, "senior",
           "Close a difficult cross-team negotiation that reached agreement.",
           "Best closing summary?",
           [
               "Great talk.",
               "Agreement: Platform ships rate-limit API by April 10; we integrate by April 17; shared success metric is p95 under 300ms. I will post the decision record and calendar the checkpoint on April 8.",
               "Hope everyone remembers.",
               "Change the deal after the meeting quietly.",
           ], "B",
           "Restate commitments, metrics, artifacts, and checkpoint date.",
           ["closing", "alignment"]),
    ]
    return pack(mid, "Cross-Team & Vendor",
                "Alignment, deadlines, and polite pushback.",
                ["IT Manager", "SRE"], items)


def one_on_one() -> dict:
    mid, p = "one-on-one", "ono"
    items = [
        mk(mid, p, 1, "mid",
           "In a 1:1, your report seems quiet and overloaded.",
           "Best opening question?",
           [
               "Why is your output low?",
               "I want to check in on workload and energy. What feels heaviest right now, and what would make the next two weeks more sustainable?",
               "Fill the whole 1:1 with your status monologue.",
               "Skip 1:1s when people look fine.",
           ], "B",
           "Open with care and a concrete sustainability ask.",
           ["1:1", "workload"]),
        mk(mid, p, 2, "senior",
           "You need to give hard feedback about missed stakeholder updates.",
           "Best framing?",
           [
               "You are bad at communication.",
               "In the last two incidents, stakeholders learned status late. The impact was avoidable escalations. Going forward I need a status note within 15 minutes of SEV start. Let's practice a template together today.",
               "Put it only in the annual review surprise.",
               "Hint vaguely and hope they notice.",
           ], "B",
           "Behavior + impact + clear future standard + support.",
           ["feedback", "communication"]),
        mk(mid, p, 3, "mid",
           "Report asks how to grow toward staff/SRE leadership.",
           "Strong coaching reply?",
           [
               "Just work harder.",
               "For the next quarter, let's target two outcomes: leading one cross-team reliability initiative and mentoring an on-call buddy. We will review evidence monthly against those outcomes.",
               "Titles are meaningless; never plan.",
               "Promise a promotion date with no criteria.",
           ], "B",
           "Growth plans need outcomes, evidence, and review cadence.",
           ["career", "coaching"]),
        mk(mid, p, 4, "junior",
           "As a report, you want more challenging work.",
           "How do you ask your manager?",
           [
               "I am bored; this job is easy.",
               "I am ready for more ownership. Could I lead the next canary rollout with your sponsorship? I will draft a plan this week and identify risks I still need help with.",
               "Threaten to leave immediately.",
               "Wait silently for someone to notice.",
           ], "B",
           "Ask for ownership with a plan and explicit sponsorship needs.",
           ["career", "ask"]),
        mk(mid, p, 5, "senior",
           "Performance is slipping due to unclear priorities across teams.",
           "Manager message in 1:1?",
           [
               "Try harder to please everyone.",
               "Your priorities are split across three stakeholders. Together we will define a ranked top three for this sprint, and I will reinforce that order with the other managers.",
               "Blame the employee only.",
               "Add more meetings.",
           ], "B",
           "Managers remove ambiguity and shield priority order.",
           ["priorities", "management"]),
        mk(mid, p, 6, "mid",
           "Report made a production mistake and feels ashamed.",
           "Supportive response?",
           [
               "You should feel bad.",
               "Thank you for owning it quickly. Mistakes happen in complex systems. Let's focus on the learning and the preventive change. I still trust you on-call — we will pair on the first shift back if you want.",
               "Remove them from on-call forever immediately.",
               "Joke about it in public Slack.",
           ], "B",
           "Psychological safety + learning + continued trust.",
           ["mistake", "safety"]),
        mk(mid, p, 7, "mid",
           "You disagree with your manager's technical direction.",
           "Respectful challenge?",
           [
               "That plan is dumb.",
               "I see the goal. My concern is blast radius without canaries. Can we walk through a safer sequence that still hits the date, or explicitly accept the risk if we skip it?",
               "Complain to the team after the 1:1.",
               "Sabotage the plan quietly.",
           ], "B",
           "Challenge with risk, alternative, and decision clarity.",
           ["disagreement", "upward"]),
        mk(mid, p, 8, "senior",
           "Mentoring session: junior freezes during incident bridge updates.",
           "Coaching line?",
           [
               "Maybe you cannot do on-call.",
               "Bridge updates are a skill. Let's script a 3-line template — impact, action, next update time — and rehearse twice this week. I will shadow your next SEV-3.",
               "Throw them into SEV-1 alone.",
               "Take over forever without teaching.",
           ], "B",
           "Teach with template, rehearsal, and shadowed practice.",
           ["mentoring", "incident"]),
        mk(mid, p, 9, "junior",
           "You need to cancel a 1:1 due to an active incident.",
           "Best note to your manager?",
           [
               "Skipping.",
               "I need to move our 1:1 — I am on an active SEV-2 bridge. Can we do 20 minutes tomorrow at 10:30, or async bullets today if that is better for you?",
               "No-show without message.",
               "Expect the manager to guess why.",
           ], "B",
           "Reschedule with reason and options.",
           ["calendar", "respect"]),
        mk(mid, p, 10, "mid",
           "Promotion conversation: report wants a title now; evidence is partial.",
           "Honest manager reply?",
           [
               "Sure, whatever.",
               "I support your trajectory. For this cycle, we still need consistent cross-team influence evidence. Here are two gaps and a 90-day plan. If we hit them, I will champion you in the next review.",
               "Never discuss promotions.",
               "Promise a title with no path.",
           ], "B",
           "Supportive honesty with gaps and a timeboxed plan.",
           ["promotion", "honesty"]),
        mk(mid, p, 11, "senior",
           "Skip-level 1:1: engineer says process is slowing delivery.",
           "Productive response?",
           [
               "Process is sacred; deal with it.",
               "Thanks for the signal. Which step creates the most delay without reducing risk? I will review it with the leads and we will either streamline it or explain the risk it prevents.",
               "Trash the process publicly same day.",
               "Ignore skip-level feedback.",
           ], "B",
           "Seek the costly step, commit to review, keep risk framing.",
           ["skip-level", "process"]),
        mk(mid, p, 12, "mid",
           "End a career 1:1 with clear next steps.",
           "Best closing?",
           [
               "Talk again someday.",
               "Next steps: you draft the initiative one-pager by Friday; I introduce you to the platform lead next week; we review progress in our 1:1 in two weeks. I will send this summary after the call.",
               "Keep goals only in your head.",
               "Add ten vague aspirations with no owners.",
           ], "B",
           "Concrete owners, dates, and a written summary.",
           ["closing", "career"]),
    ]
    return pack(mid, "1:1 & Mentoring",
                "Feedback, career talk, and coaching phrases.",
                ["IT Manager"], items)


# ---------------------------------------------------------------------------
# Extra items for existing ready modules
# ---------------------------------------------------------------------------

EXTRA_INCIDENT = [
    mk("incident-oncall", "inc", 11, "senior",
       "During a SEV-1, marketing wants to publish a cheerful 'all good' social post.",
       "What do you tell them?",
       [
           "Sure, post anything positive.",
           "Please hold public posts until we confirm stable recovery for 30 minutes. Draft customer-safe language with me: acknowledge disruption, state we are restoring service, avoid root-cause speculation.",
           "Let them post blame on engineering.",
           "Ignore marketing entirely.",
       ], "B",
       "Coordinate messaging and avoid premature 'all clear'.",
       ["comms", "sev1"]),
    mk("incident-oncall", "inc", 12, "mid",
       "You suspect a dependency outage but lack proof yet.",
       "Careful bridge phrasing?",
       [
           "It is definitely their fault.",
           "Hypothesis: upstream auth latency may be contributing. I am validating with dependency dashboards now and will confirm or retire this theory in three minutes.",
           "Guess loudly without checking.",
           "Stay silent about possible causes.",
       ], "B",
           "Label hypotheses and give a validation checkpoint.",
           ["hypothesis", "bridge"]),
    mk("incident-oncall", "inc", 13, "junior",
       "A noisy alert keeps paging but user impact is zero.",
       "What do you say in the on-call channel?",
       [
           "Alerts are always sacred; never touch them.",
           "This alert has no user impact. I am acknowledging and opening a ticket to tune the threshold after the shift. Continuing to watch true customer symptoms.",
           "Disable all alerting permanently.",
           "Wake the whole company for every noise page.",
       ], "B",
       "Reduce noise with ownership while protecting signal.",
       ["alert-noise", "oncall"]),
    mk("incident-oncall", "inc", 14, "mid",
       "Customer success asks for per-customer impact during mitigation.",
       "Best response while still fixing?",
       [
           "I cannot talk to you during incidents ever.",
           "I can share aggregate impact now: about 9% checkout failures globally. Per-customer lists will take longer; Mira owns that extract and will post in 20 minutes while I keep mitigating.",
           "Invent precise per-customer numbers.",
           "Tell CS to stop asking.",
       ], "B",
       "Give what you can now; assign the deeper ask without dropping mitigation.",
       ["stakeholders", "delegation"]),
    mk("incident-oncall", "inc", 15, "senior",
       "After mitigation, someone wants to 'improve things live' with a risky hot fix.",
       "What do you say?",
       [
           "Yes, keep changing production casually.",
           "Service is stable. Let's freeze non-essential changes for 60 minutes, watch golden signals, and take risky improvements through a reviewed change with canary. Stability first.",
           "Let anyone deploy anything as a reward.",
           "Immediately start a rewrite.",
       ], "B",
       "Post-mitigation change freeze protects recovery.",
       ["stability", "change-freeze"]),
]

EXTRA_MANAGER = [
    mk("manager-updates", "mgr", 11, "mid",
       "Your manager asks for a 'quick gut feel' on a risky launch.",
       "Best reply?",
       [
           "I guess it is fine.",
           "Gut feel is cautious. Confidence is medium: canary looks good, but we lack load-test coverage for peak. Recommendation: delay 48 hours for a targeted test, or launch with a rapid rollback owner on bridge.",
           "Refuse to give any opinion.",
           "Guarantee zero risk forever.",
       ], "B",
       "Translate gut feel into confidence, gap, and options.",
       ["risk", "recommendation"]),
    mk("manager-updates", "mgr", 12, "senior",
       "Headcount was cut mid-quarter. Your manager asks what to de-scope.",
       "Strong answer?",
       [
           "We will still do everything with heroes.",
           "With one fewer engineer, I recommend pausing the nice-to-have reporting UI and protecting checkout reliability and the partner API. I will send a revised roadmap with customer impact notes today.",
           "Cut on-call coverage first.",
           "Hide the constraint from stakeholders.",
       ], "B",
       "Make explicit tradeoffs tied to customer impact.",
       ["headcount", "descope"]),
    mk("manager-updates", "mgr", 13, "junior",
       "You need your manager to unblock access to a production dashboard.",
       "Clear ask?",
       [
           "Access please.",
           "I need read access to the checkout Grafana folder to finish the weekly reliability report by Thursday. Could you approve the access request ticket LINK today?",
           "Try random credentials.",
           "Ask every week forever without a ticket.",
       ], "B",
       "Ask includes why, deadline, and the action artifact.",
       ["ask", "access"]),
    mk("manager-updates", "mgr", 14, "mid",
       "A peer team is taking credit for your reliability win in a leadership channel.",
       "Professional correction?",
       [
           "Call them liars publicly.",
           "Glad the outcome helped customers. For accuracy: detection work and rollback were led by our team with Platform support on dashboards. Happy to co-write a short shared summary if useful.",
           "Stay silent forever.",
           "Start a flame war.",
       ], "B",
       "Correct the record calmly and invite shared narrative.",
       ["credit", "tone"]),
    mk("manager-updates", "mgr", 15, "senior",
       "Quarterly business review: you have 90 seconds for reliability.",
       "Best spoken summary?",
       [
           "We clicked many buttons and looked at graphs.",
           "Reliability: checkout availability 99.95% vs 99.9% target; two SEV-2s, both mitigated under 30 minutes; top risk is DB CPU growth — decision needed on scale-up budget this month.",
           "Read a 20-page appendix aloud.",
           "Say no risks exist.",
       ], "B",
       "Metric vs target, incidents, top risk, decision ask — all in one breath.",
       ["QBR", "executive"]),
]

EXTRA_BEHAVIORAL = [
    mk("interview-behavioral", "beh", 11, "mid",
       "Tell me about a time you improved a process, not just a system.",
       "Strong STAR-style answer?",
       [
           "I like processes.",
           "Situation: incident updates were inconsistent. Task: I owned a clearer bridge protocol. Action: I introduced a 3-line update template and ran two drills. Result: stakeholder confusion dropped and average first meaningful update fell from 12 minutes to 4.",
           "I attended a process workshop once.",
           "Processes do not matter for engineers.",
       ], "B",
       "Process stories still need Situation, Task, Action, Result with metrics.",
       ["STAR", "process"]),
    mk("interview-behavioral", "beh", 12, "senior",
       "Describe a time you had to say no to a senior stakeholder.",
       "Best answer?",
       [
           "I never say no to seniors.",
           "A VP wanted to skip canaries for a launch. I explained blast-radius risk, offered a 5% canary with auto-rollback that still hit the date, and got agreement. We caught a latent bug in canary and avoided customer impact.",
           "I said no and walked out.",
           "I complained on social media.",
       ], "B",
       "Show courage with alternatives and a positive outcome.",
       ["pushback", "stakeholder"]),
    mk("interview-behavioral", "beh", 13, "junior",
       "How do you handle ambiguous requirements?",
           "Best response?",
       [
           "I wait forever for perfect specs.",
           "I write down assumptions, propose a thin slice, confirm with the stakeholder quickly, and iterate. Recently that turned a vague 'make it faster' request into a p95 latency target we could measure.",
           "I invent a huge project silently.",
           "I ignore ambiguity and hope.",
       ], "B",
           "Ambiguity handling = assumptions, thin slice, confirmation, metrics.",
           ["ambiguity", "product"]),
    mk("interview-behavioral", "beh", 14, "mid",
       "Tell me about mentoring someone through failure.",
       "Strong answer?",
       [
           "I told them not to fail.",
           "A junior froze on their first bridge update. I debriefed privately, gave a template, rehearsed, and shadowed the next shift. Within two weeks they delivered clear updates independently.",
           "I took over permanently so they would not learn.",
           "I documented their failure in public Slack.",
       ], "B",
       "Mentoring through failure needs safety, structure, and measured growth.",
       ["mentoring", "failure"]),
    mk("interview-behavioral", "beh", 15, "senior",
       "Why are you leaving your current role?",
       "Most professional answer?",
       [
           "My manager is terrible and the company is dying.",
           "I am proud of the reliability gains we delivered. I am looking for a larger multi-region scope and closer partnership between platform and product, which this role offers.",
           "I just want more money only.",
           "I got bored of working.",
       ], "B",
       "Forward-looking, respectful, tied to the new role's scope.",
       ["motivation", "transition"]),
]


def append_extras(module_id: str, extras: list[dict]) -> None:
    path = MODULES / f"{module_id}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    existing_ids = {i["id"] for i in data["items"]}
    for item in extras:
        if item["id"] not in existing_ids:
            data["items"].append(item)
    data["status"] = "ready"
    data["itemCount"] = len(data["items"])
    write_module(data)


def update_manifest() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    for meta in manifest["modules"]:
        path = MODULES / f"{meta['id']}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        meta["status"] = data["status"]
        meta["itemCount"] = data["itemCount"]
        meta["description"] = data["description"]
        meta["title"] = data["title"]
        meta["persona"] = data["persona"]
    manifest["version"] = "1.1.0"
    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("updated manifest.json")


def main() -> None:
    for builder in (
        interview_technical,
        offer_negotiation,
        standup_sync,
        slack_email,
        presentation_demo,
        pr_code_review,
        postmortem,
        cross_team,
        one_on_one,
    ):
        write_module(builder())

    append_extras("incident-oncall", EXTRA_INCIDENT)
    append_extras("manager-updates", EXTRA_MANAGER)
    append_extras("interview-behavioral", EXTRA_BEHAVIORAL)
    update_manifest()


if __name__ == "__main__":
    main()
