#!/usr/bin/env bash
# Ubuntu one-shot deploy:
#   git pull
#   ./scripts/deploy.sh
#
# Installs Docker if missing, creates .env once, builds & starts the stack.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_sudo() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    die "Need root/sudo to install Docker"
  fi
}

rand_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n'
  else
    head -c 48 /dev/urandom | base64 | tr -d '\n'
  fi
}

rand_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '\n=/+' | cut -c1-24
  else
    head -c 18 /dev/urandom | base64 | tr -d '\n=/+' | cut -c1-24
  fi
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    log "Starting Docker daemon..."
    need_sudo systemctl enable --now docker || true
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    die "Docker installed but not usable. Try: sudo usermod -aG docker \$USER && newgrp docker"
  fi

  log "Installing Docker (Ubuntu)..."
  need_sudo apt-get update -y
  need_sudo apt-get install -y ca-certificates curl
  curl -fsSL https://get.docker.com | need_sudo sh
  need_sudo systemctl enable --now docker
  if [[ "$(id -u)" -ne 0 ]]; then
    need_sudo usermod -aG docker "$USER" || true
  fi

  if ! docker info >/dev/null 2>&1; then
    die "Docker installed. Log out/in (or run: newgrp docker), then re-run ./scripts/deploy.sh"
  fi
}

lan_ip() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true
    return 0
  fi
  hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | head -n1
}

detect_app_url() {
  local port="$1"
  local ip
  ip="$(lan_ip)"
  if [[ -n "$ip" ]]; then
    printf 'https://%s:%s' "$ip" "$port"
  else
    printf 'https://127.0.0.1:%s' "$port"
  fi
}

install_mkcert() {
  if command -v mkcert >/dev/null 2>&1; then
    return 0
  fi
  local os arch
  case "$(uname -s)" in
    Linux) os=linux ;;
    Darwin) os=darwin ;;
    *) die "mkcert: sistem $(uname -s) tidak didukung" ;;
  esac
  case "$(uname -m)" in
    x86_64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) die "mkcert: arsitektur $(uname -m) tidak didukung" ;;
  esac
  local ver=v1.4.4
  local tmp
  tmp="$(mktemp)"
  log "Installing mkcert ${ver}..."
  curl -fsSL "https://github.com/FiloSottile/mkcert/releases/download/${ver}/mkcert-${ver}-${os}-${arch}" -o "$tmp"
  need_sudo install -m 755 "$tmp" /usr/local/bin/mkcert
  rm -f "$tmp"
}

ensure_certs() {
  install_mkcert
  local ip
  ip="$(lan_ip)"
  [[ -n "$ip" ]] || die "Tidak menemukan IP LAN. Set APP_URL manual tidak cukup: mkcert butuh IP privat mesin ini."

  mkdir -p certs
  local stamp="certs/.names"
  local names="${ip} localhost 127.0.0.1"
  if [[ -f certs/cert.pem && -f certs/key.pem && -f certs/rootCA.pem && "$(cat "$stamp" 2>/dev/null || true)" == "$names" ]]; then
    printf '%s' "$ip"
    return 0
  fi

  log "Membuat sertifikat lokal untuk ${ip}..."
  (
    cd certs
    mkcert -cert-file cert.pem -key-file key.pem "$ip" localhost 127.0.0.1
  )
  cp "$(mkcert -CAROOT)/rootCA.pem" certs/rootCA.pem
  chmod 644 certs/cert.pem certs/key.pem certs/rootCA.pem
  printf '%s\n' "$names" > "$stamp"
  printf '%s' "$ip"
}

upsert_env() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" .env; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
      sed -i '' "s|^${key}=.*|${key}=${value}|" .env
    else
      sed -i "s|^${key}=.*|${key}=${value}|" .env
    fi
  else
    printf '%s=%s\n' "$key" "$value" >> .env
  fi
}

sync_https_urls() {
  local ip="$1"
  local port="$2"
  local https_url="https://${ip}:${port}"
  local current="${APP_URL:-}"

  if [[ "$current" == *":3000" || "$current" == *":3000/" ]]; then
    log ".env pengembangan port 3000 dibiarkan. URL HTTPS hanya untuk deploy port ${port}."
    return 0
  fi

  if [[ -n "$current" && "$current" != http://* && "$current" != "$https_url" ]]; then
    log "APP_URL sudah khusus (${current}) — tidak ditimpa"
    return 0
  fi

  log "APP_URL -> ${https_url}"
  upsert_env APP_URL "$https_url"
  upsert_env AUTH_URL "$https_url"
  upsert_env NEXTAUTH_URL "$https_url"
  upsert_env CA_PORT "${CA_PORT:-8011}"
  APP_URL="$https_url"
  AUTH_URL="$https_url"
  NEXTAUTH_URL="$https_url"
}

ensure_env() {
  if [[ -f .env ]]; then
    log ".env already exists — keeping it"
    return
  fi

  log "Creating .env..."
  local secret password app_url port
  port=8010
  secret="$(rand_secret)"
  password="$(rand_password)"
  app_url="$(detect_app_url "$port")"

  cat > .env <<EOF
# Generated by scripts/deploy.sh — HTTPS via mkcert. Edit APP_URL if you use a domain.
APP_PORT=${port}
APP_URL=${app_url}

POSTGRES_USER=as_english
POSTGRES_PASSWORD=${password}
POSTGRES_DB=as_english

DATABASE_URL=postgresql://as_english:${password}@db:5432/as_english?schema=public
AUTH_SECRET=${secret}
AUTH_URL=${app_url}
NEXTAUTH_URL=${app_url}
CA_PORT=8011

SEED_ON_START=true
EOF

  chmod 600 .env
  log "Wrote .env (APP_URL=${app_url})"
}

wait_healthy() {
  local port="${APP_PORT:-8010}"
  local i=0

  log "Waiting for web container..."
  until docker compose ps --status running 2>/dev/null | grep -q as_english_web; do
    i=$((i + 1))
    [[ "$i" -lt 90 ]] || die "Web container did not start"
    sleep 2
  done

  i=0
  log "Waiting for HTTP and HTTPS on :${port}..."
  until curl -fsS "http://127.0.0.1:${port}/" >/dev/null 2>&1 \
    && curl -fsS --cacert certs/rootCA.pem "https://127.0.0.1:${port}/" >/dev/null 2>&1; do
    i=$((i + 1))
    if [[ "$i" -ge 90 ]]; then
      docker compose logs --tail=80 web proxy edge || true
      die "App did not become ready on port ${port}"
    fi
    sleep 2
  done
}

ensure_curl() {
  if command -v curl >/dev/null 2>&1; then
    return 0
  fi
  log "Installing curl..."
  need_sudo apt-get update -y
  need_sudo apt-get install -y curl
}

main() {
  ensure_docker
  ensure_curl
  local ip
  ip="$(ensure_certs)"
  ensure_env

  # shellcheck disable=SC1091
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  sync_https_urls "$ip" "${APP_PORT:-8010}"

  # shellcheck disable=SC1091
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  log "Building & starting containers..."
  docker compose up -d --build --remove-orphans

  wait_healthy

  local ca_port="${CA_PORT:-8011}"
  log "Deploy OK"
  echo "  HTTP:  http://${ip}:${APP_PORT:-8010}/"
  echo "  HTTPS: ${APP_URL}"
  echo "  CA:    http://${ip}:${ca_port}/rootCA.pem"
  echo "  HP:    unduh CA itu, pasang sebagai sertifikat CA, lalu buka URL di atas."
  echo "         Android: Setelan > Keamanan > Enkripsi dan kredensial > Pasang sertifikat > Sertifikat CA"
  echo "         iPhone: unduh, pasang profil, lalu Setelan > Umum > Tentang > Pengaturan Kepercayaan Sertifikat"
  echo "  Demo:  demo@asenglish.local / demo1234"
  echo "  Logs:  docker compose logs -f"
  echo "  Stop:  docker compose down"
}

main "$@"
