#!/usr/bin/env bash
# Ubuntu one-shot deploy:
#   git pull
#   ./scripts/deploy.sh
#
# Installs Docker if missing, creates .env once, builds & starts the stack.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_sudo() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    die "Need root/sudo to install Docker"
  fi
}

rand_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n'
  else
    head -c 48 /dev/urandom | base64 | tr -d '\n'
  fi
}

rand_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '\n=/+' | cut -c1-24
  else
    head -c 18 /dev/urandom | base64 | tr -d '\n=/+' | cut -c1-24
  fi
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    log "Starting Docker daemon..."
    need_sudo systemctl enable --now docker || true
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    die "Docker installed but not usable. Try: sudo usermod -aG docker \$USER && newgrp docker"
  fi

  log "Installing Docker (Ubuntu)..."
  need_sudo apt-get update -y
  need_sudo apt-get install -y ca-certificates curl
  curl -fsSL https://get.docker.com | need_sudo sh
  need_sudo systemctl enable --now docker
  if [[ "$(id -u)" -ne 0 ]]; then
    need_sudo usermod -aG docker "$USER" || true
  fi

  if ! docker info >/dev/null 2>&1; then
    die "Docker installed. Log out/in (or run: newgrp docker), then re-run ./scripts/deploy.sh"
  fi
}

detect_app_url() {
  if [[ -n "${APP_URL:-}" ]]; then
    printf '%s' "$APP_URL"
    return
  fi
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -n "$ip" ]]; then
    printf 'http://%s:3000' "$ip"
  else
    printf 'http://localhost:3000'
  fi
}

ensure_env() {
  if [[ -f .env ]]; then
    log ".env already exists — keeping it"
    return
  fi

  log "Creating .env..."
  local secret password app_url
  secret="$(rand_secret)"
  password="$(rand_password)"
  app_url="$(detect_app_url)"

  cat > .env <<EOF
# Generated by scripts/deploy.sh — edit APP_URL if you use a domain.
APP_PORT=3000
APP_URL=${app_url}

POSTGRES_USER=as_english
POSTGRES_PASSWORD=${password}
POSTGRES_DB=as_english
POSTGRES_PORT=5432

DATABASE_URL=postgresql://as_english:${password}@db:5432/as_english?schema=public
AUTH_SECRET=${secret}
AUTH_URL=${app_url}
NEXTAUTH_URL=${app_url}

SEED_ON_START=true
EOF

  chmod 600 .env
  log "Wrote .env (APP_URL=${app_url})"
}

wait_healthy() {
  local port="${APP_PORT:-3000}"
  local i=0

  log "Waiting for web container..."
  until docker compose ps --status running 2>/dev/null | grep -q as_english_web; do
    i=$((i + 1))
    [[ "$i" -lt 90 ]] || die "Web container did not start"
    sleep 2
  done

  i=0
  log "Waiting for app on :${port}..."
  until curl -fsS "http://127.0.0.1:${port}/" >/dev/null 2>&1; do
    i=$((i + 1))
    if [[ "$i" -ge 90 ]]; then
      docker compose logs --tail=80 web || true
      die "App did not become ready on port ${port}"
    fi
    sleep 2
  done
}

ensure_curl() {
  if command -v curl >/dev/null 2>&1; then
    return 0
  fi
  log "Installing curl..."
  need_sudo apt-get update -y
  need_sudo apt-get install -y curl
}

main() {
  ensure_docker
  ensure_curl
  ensure_env

  # shellcheck disable=SC1091
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  log "Building & starting containers..."
  docker compose up -d --build --remove-orphans

  wait_healthy

  log "Deploy OK"
  echo "  URL:   ${APP_URL:-http://localhost:3000}"
  echo "  Demo:  demo@asenglish.local / demo1234"
  echo "  Logs:  docker compose logs -f"
  echo "  Stop:  docker compose down"
}

main "$@"
